In [2]:
import pandas as pd

<br> <br>

## Overview

In [88]:
currency = pd.read_csv("../data/tradingeconomics/Overview/currency.csv", encoding="utf-16")

currency["Date"] = pd.to_datetime(currency["Date"], dayfirst=True, errors='coerce')

currency

          Symbol       Date     Open     High      Low   Close
0     USDBDT:CUR 2026-01-12  122.290  122.485  122.005  122.20
1     USDBDT:CUR 2026-01-09  122.200  122.200  122.200  122.20
2     USDBDT:CUR 2026-01-08  122.295  122.485  122.010  122.20
3     USDBDT:CUR 2026-01-07  122.285  122.475  122.010  122.20
4     USDBDT:CUR 2026-01-06  122.295  122.485  122.010  122.20
...          ...        ...      ...      ...      ...     ...
1330  USDBDT:CUR 2021-01-22   84.290   84.620   84.150   84.15
1331  USDBDT:CUR 2021-01-21   84.800   84.800   84.790   84.79
1332  USDBDT:CUR 2021-01-20   84.790   84.800   84.290   84.29
1333  USDBDT:CUR 2021-01-19   84.800   84.800   84.280   84.28
1334  USDBDT:CUR 2021-01-18   84.790   84.800   84.790   84.80

[1335 rows x 6 columns]

In [ ]:
stock_market = pd.read_csv("../data/tradingeconomics/Overview/stock_market.csv", encoding="utf-16")

stock_market["Date"] = pd.to_datetime(stock_market["Date"], dayfirst=True, errors='coerce')

stock_market

     Symbol       Date     Open     High      Low    Close
0  DSEX:IND 2026-01-12  4939.59  4950.07  4918.67  4942.05
1  DSEX:IND 2026-01-11  4998.55  5002.05  4939.59  4939.59
2  DSEX:IND 2026-01-08  4992.70  5011.96  4991.12  4998.55
3  DSEX:IND 2026-01-07  4953.61  5002.81  4953.61  4992.70
4  DSEX:IND 2026-01-06  4954.87  4983.67  4942.22  4953.61

In [ ]:
annual_growth_rate = pd.read_csv("../data/tradingeconomics/Overview/annual_growth_rate.csv")

annual_growth_rate["DateTime"] = pd.to_datetime(annual_growth_rate["DateTime"], errors='coerce')

annual_growth_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP Annual Growth Rate,1994-06-30,4.08,Yearly,BangladeshGDPYoY,2025-05-22T03:04:00
1,Bangladesh,GDP Annual Growth Rate,1995-06-30,4.93,Yearly,BangladeshGDPYoY,2025-05-22T03:04:00
2,Bangladesh,GDP Annual Growth Rate,1996-06-30,4.62,Yearly,BangladeshGDPYoY,2025-05-22T03:04:00
3,Bangladesh,GDP Annual Growth Rate,1997-06-30,5.39,Yearly,BangladeshGDPYoY,2025-05-22T03:04:00
4,Bangladesh,GDP Annual Growth Rate,1998-06-30,5.23,Yearly,BangladeshGDPYoY,2025-05-22T03:04:00

In [ ]:
unemployment_rate = pd.read_csv("../data/tradingeconomics/Overview/unemployment_rate.csv")

unemployment_rate["DateTime"] = pd.to_datetime(unemployment_rate["DateTime"], errors='coerce')

unemployment_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Unemployment Rate,1991-12-31,2.2,Yearly,BangladeshUR,2017-06-06T11:46:00
1,Bangladesh,Unemployment Rate,1992-12-31,2.3,Yearly,BangladeshUR,2024-02-06T02:39:00
2,Bangladesh,Unemployment Rate,1993-12-31,2.3,Yearly,BangladeshUR,2024-02-06T02:39:00
3,Bangladesh,Unemployment Rate,1994-12-31,2.4,Yearly,BangladeshUR,2024-02-06T02:39:00
4,Bangladesh,Unemployment Rate,1995-12-31,2.4,Yearly,BangladeshUR,2024-02-06T02:39:00

In [ ]:
inflation_rate = pd.read_csv("../data/tradingeconomics/Overview/inflation_rate.csv")

inflation_rate["DateTime"] = pd.to_datetime(inflation_rate["DateTime"], errors='coerce')

inflation_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Inflation Rate,1994-07-31,5.50,Monthly,BangladeshIR,2016-04-05T14:51:00
1,Bangladesh,Inflation Rate,1994-08-31,7.11,Monthly,BangladeshIR,2016-04-05T14:51:00
2,Bangladesh,Inflation Rate,1994-09-30,6.84,Monthly,BangladeshIR,2016-04-05T14:51:00
3,Bangladesh,Inflation Rate,1994-10-31,8.30,Monthly,BangladeshIR,2016-04-05T14:51:00
4,Bangladesh,Inflation Rate,1994-11-30,7.62,Monthly,BangladeshIR,2016-04-05T14:51:00

In [ ]:
interest_rate = pd.read_csv("../data/tradingeconomics/Overview/interest_rate.csv")

interest_rate["DateTime"] = pd.to_datetime(interest_rate["DateTime"], errors='coerce')

interest_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Interest Rate,2008-01-31,8.5,Daily,BangladeshIntRate,2011-06-27T00:00:00
1,Bangladesh,Interest Rate,2008-02-29,8.5,Daily,BangladeshIntRate,2011-06-27T00:00:00
2,Bangladesh,Interest Rate,2008-03-31,8.5,Daily,BangladeshIntRate,2011-06-27T00:00:00
3,Bangladesh,Interest Rate,2008-04-30,8.5,Daily,BangladeshIntRate,2011-06-27T00:00:00
4,Bangladesh,Interest Rate,2008-05-31,8.5,Daily,BangladeshIntRate,2011-06-27T00:00:00

In [ ]:
balance_of_trade = pd.read_csv("../data/tradingeconomics/Overview/balance_of_trade.csv")

balance_of_trade["DateTime"] = pd.to_datetime(balance_of_trade["DateTime"], errors='coerce')
balance_of_trade["LastUpdate"] = pd.to_datetime(balance_of_trade["LastUpdate"], errors='coerce')

balance_of_trade

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Balance of Trade,1976-03-31,-1.2,Monthly,BangladeshBT,2014-08-26 18:11:00
1,Bangladesh,Balance of Trade,1976-04-30,-0.6,Monthly,BangladeshBT,2014-08-26 18:11:00
2,Bangladesh,Balance of Trade,1976-05-31,-0.6,Monthly,BangladeshBT,2014-11-16 21:27:00
3,Bangladesh,Balance of Trade,1976-06-30,-1.4,Monthly,BangladeshBT,2014-08-26 18:11:00
4,Bangladesh,Balance of Trade,1976-07-31,-0.7,Monthly,BangladeshBT,2014-08-26 18:11:00

In [ ]:
current_account = pd.read_csv("../data/tradingeconomics/Overview/current_account.csv")

current_account["DateTime"] = pd.to_datetime(current_account["DateTime"], errors='coerce')
current_account["LastUpdate"] = pd.to_datetime(current_account["LastUpdate"], errors='coerce')

current_account

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Current Account,2005-06-30,-557.0,Monthly,BangladeshCA,2011-06-27
1,Bangladesh,Current Account,2006-06-30,824.0,Monthly,BangladeshCA,2011-06-27
2,Bangladesh,Current Account,2007-06-30,952.0,Monthly,BangladeshCA,2011-06-27
3,Bangladesh,Current Account,2008-06-30,680.0,Monthly,BangladeshCA,2011-06-27
4,Bangladesh,Current Account,2008-09-30,366.0,Monthly,BangladeshCA,2011-06-27

In [ ]:
current_account_to_GDP = pd.read_csv("../data/tradingeconomics/Overview/current_account_to_GDP.csv")

current_account_to_GDP["DateTime"] = pd.to_datetime(current_account_to_GDP["DateTime"], errors='coerce')
current_account_to_GDP["LastUpdate"] = pd.to_datetime(current_account_to_GDP["LastUpdate"], errors='coerce')

current_account_to_GDP

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Current Account to GDP,1980-12-31,-0.8,Yearly,BGDCA2GDP,2025-01-28 07:24:00
1,Bangladesh,Current Account to GDP,1981-12-31,-1.8,Yearly,BGDCA2GDP,2025-01-28 07:24:00
2,Bangladesh,Current Account to GDP,1982-12-31,-2.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
3,Bangladesh,Current Account to GDP,1983-12-31,-2.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
4,Bangladesh,Current Account to GDP,1984-12-31,-1.9,Yearly,BGDCA2GDP,2025-01-28 07:24:00

In [12]:
government_debt_to_GDP = pd.read_csv("../data/tradingeconomics/Overview/government_debt_to_GDP.csv")

government_debt_to_GDP["DateTime"] = pd.to_datetime(government_debt_to_GDP["DateTime"], errors='coerce')
government_debt_to_GDP["LastUpdate"] = pd.to_datetime(government_debt_to_GDP["LastUpdate"], errors='coerce')

government_debt_to_GDP

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Debt to GDP,1995-12-31,49.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
1,Bangladesh,Government Debt to GDP,1996-12-31,43.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
2,Bangladesh,Government Debt to GDP,1997-12-31,43.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
3,Bangladesh,Government Debt to GDP,1998-12-31,40.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
4,Bangladesh,Government Debt to GDP,1999-12-31,42.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
5,Bangladesh,Government Debt to GDP,2000-12-31,46.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
6,Bangladesh,Government Debt to GDP,2001-12-31,46.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
7,Bangladesh,Government Debt to GDP,2002-12-31,50.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
8,Bangladesh,Government Debt to GDP,2003-12-31,49.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
9,Bangladesh,Government Debt to GDP,2004-12-31,48.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
10,Bangladesh,Government Debt to GDP,2005-12-31,46.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
11,Bangladesh,Government Debt to GDP,2006-12-31,40.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
12,Bangladesh,Government Debt to GDP,2007-12-31,38.6,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
13,Bangladesh,Government Debt to GDP,2008-12-31,37.1,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
14,Bangladesh,Government Debt to GDP,2009-12-31,35.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
15,Bangladesh,Government Debt to GDP,2010-12-31,32.3,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
16,Bangladesh,Government Debt to GDP,2011-12-31,32.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
17,Bangladesh,Government Debt to GDP,2012-12-31,31.8,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
18,Bangladesh,Government Debt to GDP,2013-12-31,30.4,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
19,Bangladesh,Government Debt to GDP,2014-12-31,29.6,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
20,Bangladesh,Government Debt to GDP,2015-12-31,27.7,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
21,Bangladesh,Government Debt to GDP,2016-12-31,27.7,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
22,Bangladesh,Government Debt to GDP,2017-12-31,27.0,Yearly,BGDDebt2GDP,2019-05-02 14:31:00
23,Bangladesh,Government Debt to GDP,2018-12-31,25.7,Yearly,BGDDebt2GDP,2023-07-14 09:49:00
24,Bangladesh,Government Debt to GDP,2019-12-31,27.0,Yearly,BGDDebt2GDP,2023-07-14 09:48:00
25,Bangladesh,Government Debt to GDP,2020-12-31,28.1,Yearly,BGDDebt2GDP,2023-07-14 09:48:00
26,Bangladesh,Government Debt to GDP,2021-12-31,29.3,Yearly,BGDDebt2GDP,2024-11-20 01:35:00
27,Bangladesh,Government Debt to GDP,2022-12-31,29.5,Yearly,BGDDebt2GDP,2024-11-20 01:35:00
28,Bangladesh,Government Debt to GDP,2023-12-31,31.6,Yearly,BGDDebt2GDP,2025-09-02 06:11:00
29,Bangladesh,Government Debt to GDP,2024-12-31,32.2,Yearly,BGDDebt2GDP,2025-09-02 06:11:00

In [13]:
government_budget = pd.read_csv("../data/tradingeconomics/Overview/government_budget.csv")

government_budget["DateTime"] = pd.to_datetime(government_budget["DateTime"], errors='coerce')
government_budget["LastUpdate"] = pd.to_datetime(government_budget["LastUpdate"], errors='coerce')

government_budget

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Budget,1991-12-31,-3.30,Yearly,BangladeshGB,2016-09-07 13:56:00
1,Bangladesh,Government Budget,1992-12-31,-2.10,Yearly,BangladeshGB,2016-09-07 13:56:00
2,Bangladesh,Government Budget,1993-12-31,-1.30,Yearly,BangladeshGB,2016-09-07 13:56:00
3,Bangladesh,Government Budget,1994-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
4,Bangladesh,Government Budget,1995-12-31,-2.20,Yearly,BangladeshGB,2015-06-12 14:23:00
5,Bangladesh,Government Budget,1996-12-31,-3.00,Yearly,BangladeshGB,2015-06-12 14:23:00
6,Bangladesh,Government Budget,1997-12-31,-2.00,Yearly,BangladeshGB,2015-06-12 14:23:00
7,Bangladesh,Government Budget,1998-12-31,-2.10,Yearly,BangladeshGB,2015-06-12 14:23:00
8,Bangladesh,Government Budget,1999-12-31,-3.20,Yearly,BangladeshGB,2015-06-12 14:23:00
9,Bangladesh,Government Budget,2000-12-31,-4.50,Yearly,BangladeshGB,2015-06-12 14:23:00
10,Bangladesh,Government Budget,2001-12-31,-4.10,Yearly,BangladeshGB,2015-06-12 14:23:00
11,Bangladesh,Government Budget,2002-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
12,Bangladesh,Government Budget,2003-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
13,Bangladesh,Government Budget,2004-12-31,-3.40,Yearly,BangladeshGB,2015-06-12 14:23:00
14,Bangladesh,Government Budget,2005-12-31,-3.40,Yearly,BangladeshGB,2015-06-12 14:23:00
15,Bangladesh,Government Budget,2006-12-31,-2.80,Yearly,BangladeshGB,2016-03-28 17:01:00
16,Bangladesh,Government Budget,2007-12-31,-2.80,Yearly,BangladeshGB,2016-03-28 17:01:00
17,Bangladesh,Government Budget,2008-12-31,-4.60,Yearly,BangladeshGB,2016-03-28 17:01:00
18,Bangladesh,Government Budget,2009-12-31,-2.80,Yearly,BangladeshGB,2017-01-04 16:22:00
19,Bangladesh,Government Budget,2010-12-31,-3.40,Yearly,BangladeshGB,2017-01-04 16:22:00
20,Bangladesh,Government Budget,2011-12-31,-3.60,Yearly,BangladeshGB,2017-01-04 16:22:00
21,Bangladesh,Government Budget,2012-12-31,-4.00,Yearly,BangladeshGB,2017-01-04 16:21:00
22,Bangladesh,Government Budget,2013-12-31,-3.60,Yearly,BangladeshGB,2017-01-04 16:21:00
23,Bangladesh,Government Budget,2014-12-31,-4.00,Yearly,BangladeshGB,2021-03-02 15:03:00
24,Bangladesh,Government Budget,2015-12-31,-4.50,Yearly,BangladeshGB,2021-03-02 15:03:00
25,Bangladesh,Government Budget,2016-12-31,-4.74,Yearly,BangladeshGB,2022-10-19 07:07:00
26,Bangladesh,Government Budget,2017-12-31,-4.76,Yearly,BangladeshGB,2022-10-19 07:07:00
27,Bangladesh,Government Budget,2018-12-31,4.78,Yearly,BangladeshGB,2022-10-19 07:07:00
28,Bangladesh,Government Budget,2019-12-31,-4.80,Yearly,BangladeshGB,2021-03-02 15:02:00
29,Bangladesh,Government Budget,2020-12-31,-5.48,Yearly,BangladeshGB,2022-10-19 07:06:00
30,Bangladesh,Government Budget,2021-12-31,-6.23,Yearly,BangladeshGB,2022-10-19 07:07:00
31,Bangladesh,Government Budget,2022-12-31,-5.06,Yearly,BangladeshGB,2025-05-26 06:11:00
32,Bangladesh,Government Budget,2023-12-31,-5.00,Yearly,BangladeshGB,2025-05-26 06:11:00
33,Bangladesh,Government Budget,2024-12-31,-4.60,Yearly,BangladeshGB,2025-05-26 06:11:00

In [14]:
corporate_tax_rate = pd.read_csv("../data/tradingeconomics/Overview/corporate_tax_rate.csv")

corporate_tax_rate["DateTime"] = pd.to_datetime(corporate_tax_rate["DateTime"], errors='coerce')
corporate_tax_rate["LastUpdate"] = pd.to_datetime(corporate_tax_rate["LastUpdate"], errors='coerce')

corporate_tax_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Corporate Tax Rate,1997-12-31,40.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
1,Bangladesh,Corporate Tax Rate,1998-12-31,40.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
2,Bangladesh,Corporate Tax Rate,1999-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
3,Bangladesh,Corporate Tax Rate,2000-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
4,Bangladesh,Corporate Tax Rate,2001-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
5,Bangladesh,Corporate Tax Rate,2002-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
6,Bangladesh,Corporate Tax Rate,2003-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
7,Bangladesh,Corporate Tax Rate,2004-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
8,Bangladesh,Corporate Tax Rate,2005-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
9,Bangladesh,Corporate Tax Rate,2006-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
10,Bangladesh,Corporate Tax Rate,2007-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
11,Bangladesh,Corporate Tax Rate,2008-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
12,Bangladesh,Corporate Tax Rate,2009-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
13,Bangladesh,Corporate Tax Rate,2010-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
14,Bangladesh,Corporate Tax Rate,2011-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
15,Bangladesh,Corporate Tax Rate,2012-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
16,Bangladesh,Corporate Tax Rate,2013-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
17,Bangladesh,Corporate Tax Rate,2014-12-31,27.5,Yearly,BGDCORPTAX,2014-03-24 10:58:00
18,Bangladesh,Corporate Tax Rate,2015-12-31,27.5,Yearly,BGDCORPTAX,2016-03-28 16:33:00
19,Bangladesh,Corporate Tax Rate,2016-12-31,25.0,Yearly,BGDCORPTAX,2016-11-25 15:32:00
20,Bangladesh,Corporate Tax Rate,2017-12-31,25.0,Yearly,BGDCORPTAX,2018-02-09 15:51:00
21,Bangladesh,Corporate Tax Rate,2018-12-31,25.0,Yearly,BGDCORPTAX,2018-02-09 15:51:00
22,Bangladesh,Corporate Tax Rate,2019-12-31,25.0,Yearly,BGDCORPTAX,2020-02-11 16:47:00
23,Bangladesh,Corporate Tax Rate,2020-12-31,25.0,Yearly,BGDCORPTAX,2021-03-02 14:43:00
24,Bangladesh,Corporate Tax Rate,2021-12-31,32.5,Yearly,BGDCORPTAX,2021-06-01 16:19:00
25,Bangladesh,Corporate Tax Rate,2022-12-31,30.0,Yearly,BGDCORPTAX,2022-10-25 01:55:00
26,Bangladesh,Corporate Tax Rate,2023-12-31,27.5,Yearly,BGDCORPTAX,2024-04-15 09:19:00
27,Bangladesh,Corporate Tax Rate,2024-12-31,27.5,Yearly,BGDCORPTAX,2024-04-15 09:15:00
28,Bangladesh,Corporate Tax Rate,2025-12-31,27.5,Yearly,BGDCORPTAX,2025-01-31 09:32:00

In [15]:
personal_income_tax_rate = pd.read_csv("../data/tradingeconomics/Overview/personal_income_Tax_Rate.csv")

personal_income_tax_rate["DateTime"] = pd.to_datetime(personal_income_tax_rate["DateTime"], errors='coerce')
personal_income_tax_rate["LastUpdate"] = pd.to_datetime(personal_income_tax_rate["LastUpdate"], errors='coerce')

personal_income_tax_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Personal Income Tax Rate,2004-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
1,Bangladesh,Personal Income Tax Rate,2005-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
2,Bangladesh,Personal Income Tax Rate,2006-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
3,Bangladesh,Personal Income Tax Rate,2007-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
4,Bangladesh,Personal Income Tax Rate,2008-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
5,Bangladesh,Personal Income Tax Rate,2009-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
6,Bangladesh,Personal Income Tax Rate,2010-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
7,Bangladesh,Personal Income Tax Rate,2011-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
8,Bangladesh,Personal Income Tax Rate,2012-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
9,Bangladesh,Personal Income Tax Rate,2013-12-31,25,Yearly,BGDIRSTAX,2014-03-25 13:17:00
10,Bangladesh,Personal Income Tax Rate,2014-12-31,30,Yearly,BGDIRSTAX,2016-03-08 18:40:00
11,Bangladesh,Personal Income Tax Rate,2015-12-31,30,Yearly,BGDIRSTAX,2016-03-08 18:40:00
12,Bangladesh,Personal Income Tax Rate,2016-12-31,30,Yearly,BGDIRSTAX,2017-01-02 16:52:00
13,Bangladesh,Personal Income Tax Rate,2017-12-31,30,Yearly,BGDIRSTAX,2018-02-09 17:34:00
14,Bangladesh,Personal Income Tax Rate,2018-12-31,30,Yearly,BGDIRSTAX,2018-02-09 17:34:00
15,Bangladesh,Personal Income Tax Rate,2019-12-31,30,Yearly,BGDIRSTAX,2020-02-13 15:14:00
16,Bangladesh,Personal Income Tax Rate,2020-12-31,30,Yearly,BGDIRSTAX,2021-05-10 17:04:00
17,Bangladesh,Personal Income Tax Rate,2021-12-31,25,Yearly,BGDIRSTAX,2021-06-02 08:36:00
18,Bangladesh,Personal Income Tax Rate,2022-12-31,25,Yearly,BGDIRSTAX,2022-10-25 01:57:00
19,Bangladesh,Personal Income Tax Rate,2023-12-31,25,Yearly,BGDIRSTAX,2024-08-19 04:28:00
20,Bangladesh,Personal Income Tax Rate,2024-12-31,25,Yearly,BGDIRSTAX,2024-08-19 04:28:00

<br> <br> 

## GDP

In [16]:
gdp_annual_growth_rate = pd.read_csv("../data/tradingeconomics/GDP/GDP_Annual_Growth_Rate.csv")

gdp_annual_growth_rate["DateTime"] = pd.to_datetime(gdp_annual_growth_rate["DateTime"], errors='coerce')
gdp_annual_growth_rate["LastUpdate"] = pd.to_datetime(gdp_annual_growth_rate["LastUpdate"], errors='coerce')

gdp_annual_growth_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP Annual Growth Rate,1994-06-30,4.08,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
1,Bangladesh,GDP Annual Growth Rate,1995-06-30,4.93,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
2,Bangladesh,GDP Annual Growth Rate,1996-06-30,4.62,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
3,Bangladesh,GDP Annual Growth Rate,1997-06-30,5.39,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
4,Bangladesh,GDP Annual Growth Rate,1998-06-30,5.23,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
5,Bangladesh,GDP Annual Growth Rate,1999-06-30,4.87,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
6,Bangladesh,GDP Annual Growth Rate,2000-06-30,5.94,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
7,Bangladesh,GDP Annual Growth Rate,2001-06-30,5.27,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
8,Bangladesh,GDP Annual Growth Rate,2002-06-30,4.42,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
9,Bangladesh,GDP Annual Growth Rate,2003-06-30,5.26,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
10,Bangladesh,GDP Annual Growth Rate,2004-06-30,6.27,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
11,Bangladesh,GDP Annual Growth Rate,2005-06-30,5.96,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
12,Bangladesh,GDP Annual Growth Rate,2006-06-30,6.63,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
13,Bangladesh,GDP Annual Growth Rate,2007-06-30,6.43,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
14,Bangladesh,GDP Annual Growth Rate,2008-06-30,6.19,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
15,Bangladesh,GDP Annual Growth Rate,2009-06-30,5.05,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
16,Bangladesh,GDP Annual Growth Rate,2010-06-30,5.57,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
17,Bangladesh,GDP Annual Growth Rate,2011-06-30,6.46,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
18,Bangladesh,GDP Annual Growth Rate,2012-06-30,6.52,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
19,Bangladesh,GDP Annual Growth Rate,2013-06-30,6.01,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
20,Bangladesh,GDP Annual Growth Rate,2014-06-30,6.06,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
21,Bangladesh,GDP Annual Growth Rate,2015-06-30,6.55,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
22,Bangladesh,GDP Annual Growth Rate,2016-06-30,7.10,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
23,Bangladesh,GDP Annual Growth Rate,2017-06-30,6.59,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
24,Bangladesh,GDP Annual Growth Rate,2018-06-30,7.32,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
25,Bangladesh,GDP Annual Growth Rate,2019-06-30,7.88,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
26,Bangladesh,GDP Annual Growth Rate,2020-06-30,3.45,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
27,Bangladesh,GDP Annual Growth Rate,2021-06-30,6.94,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
28,Bangladesh,GDP Annual Growth Rate,2022-06-30,7.10,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
29,Bangladesh,GDP Annual Growth Rate,2023-06-30,5.78,Yearly,BangladeshGDPYoY,2025-05-22 03:04:00
30,Bangladesh,GDP Annual Growth Rate,2024-06-30,4.22,Yearly,BangladeshGDPYoY,2025-11-13 03:22:00
31,Bangladesh,GDP Annual Growth Rate,2025-06-30,3.97,Yearly,BangladeshGDPYoY,2025-11-13 03:22:00

In [17]:
gdp = pd.read_csv("../data/tradingeconomics/GDP/GDP.csv")

gdp["DateTime"] = pd.to_datetime(gdp["DateTime"], errors='coerce')
gdp["LastUpdate"] = pd.to_datetime(gdp["LastUpdate"], errors='coerce')

gdp

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP,1960-12-31,4.27,Yearly,BangladeshGDP,2019-07-01 15:48:00
1,Bangladesh,GDP,1961-12-31,4.82,Yearly,BangladeshGDP,2019-07-01 15:48:00
2,Bangladesh,GDP,1962-12-31,5.08,Yearly,BangladeshGDP,2019-07-01 15:48:00
3,Bangladesh,GDP,1963-12-31,5.32,Yearly,BangladeshGDP,2019-07-01 15:48:00
4,Bangladesh,GDP,1964-12-31,5.39,Yearly,BangladeshGDP,2019-07-01 15:48:00
...,...,...,...,...,...,...,...
60,Bangladesh,GDP,2020-12-31,373.98,Yearly,BangladeshGDP,2024-07-02 01:52:00
61,Bangladesh,GDP,2021-12-31,416.27,Yearly,BangladeshGDP,2024-07-01 08:02:00
62,Bangladesh,GDP,2022-12-31,460.13,Yearly,BangladeshGDP,2024-07-01 08:02:00
63,Bangladesh,GDP,2023-12-31,437.42,Yearly,BangladeshGDP,2024-07-01 13:22:00
64,Bangladesh,GDP,2024-12-31,450.12,Yearly,BangladeshGDP,2025-07-01 14:52:00

In [18]:
gdp_constant_prices = pd.read_csv("../data/tradingeconomics/GDP/GDP_Constant_Prices.csv")

gdp_constant_prices["DateTime"] = pd.to_datetime(gdp_constant_prices["DateTime"], errors='coerce')
gdp_constant_prices["LastUpdate"] = pd.to_datetime(gdp_constant_prices["LastUpdate"], errors='coerce')

gdp_constant_prices

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP Constant Prices,2016-06-30,20758.2,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
1,Bangladesh,GDP Constant Prices,2017-06-30,22126.2,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
2,Bangladesh,GDP Constant Prices,2018-06-30,23745.7,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
3,Bangladesh,GDP Constant Prices,2019-06-30,25617.4,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
4,Bangladesh,GDP Constant Prices,2020-06-30,26500.6,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
5,Bangladesh,GDP Constant Prices,2021-06-30,28339.4,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
6,Bangladesh,GDP Constant Prices,2022-06-30,30351.5,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
7,Bangladesh,GDP Constant Prices,2023-06-30,32104.3,Yearly,BANGLADESHGDPCONPRI,2025-05-22 02:55:00
8,Bangladesh,GDP Constant Prices,2024-06-30,33460.2,Yearly,BANGLADESHGDPCONPRI,2025-11-13 03:29:00
9,Bangladesh,GDP Constant Prices,2025-06-30,34790.0,Yearly,BANGLADESHGDPCONPRI,2025-11-13 03:29:00

In [19]:
gross_national_product = pd.read_csv("../data/tradingeconomics/GDP/Gross_National_Product.csv")

gross_national_product["DateTime"] = pd.to_datetime(gross_national_product["DateTime"], errors='coerce')
gross_national_product["LastUpdate"] = pd.to_datetime(gross_national_product["LastUpdate"], errors='coerce')

gross_national_product

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Gross National Product,2016-06-30,21730.8,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
1,Bangladesh,Gross National Product,2017-06-30,22890.2,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
2,Bangladesh,Gross National Product,2018-06-30,24695.3,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
3,Bangladesh,Gross National Product,2019-06-30,26666.7,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
4,Bangladesh,Gross National Product,2020-06-30,27597.6,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
5,Bangladesh,Gross National Product,2021-06-30,29831.1,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
6,Bangladesh,Gross National Product,2022-06-30,31553.9,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
7,Bangladesh,Gross National Product,2023-06-30,33385.7,Yearly,BANGLADESHGRONATPRO,2025-05-22 05:35:00
8,Bangladesh,Gross National Product,2024-06-30,34901.1,Yearly,BANGLADESHGRONATPRO,2025-11-13 03:55:00
9,Bangladesh,Gross National Product,2025-06-30,36734.6,Yearly,BANGLADESHGRONATPRO,2025-11-13 04:09:00

In [20]:
gross_fixed_capital_formation = pd.read_csv("../data/tradingeconomics/GDP/Gross_Fixed_Capital_Formation.csv")

gross_fixed_capital_formation["DateTime"] = pd.to_datetime(gross_fixed_capital_formation["DateTime"], errors='coerce')
gross_fixed_capital_formation["LastUpdate"] = pd.to_datetime(gross_fixed_capital_formation["LastUpdate"], errors='coerce')

gross_fixed_capital_formation

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Gross Fixed Capital Formation,2016-06-30,6277.2,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
1,Bangladesh,Gross Fixed Capital Formation,2017-06-30,6802.0,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
2,Bangladesh,Gross Fixed Capital Formation,2018-06-30,7627.3,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
3,Bangladesh,Gross Fixed Capital Formation,2019-06-30,8152.0,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
4,Bangladesh,Gross Fixed Capital Formation,2020-06-30,8473.7,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
5,Bangladesh,Gross Fixed Capital Formation,2021-06-30,9159.3,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
6,Bangladesh,Gross Fixed Capital Formation,2022-06-30,10226.7,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
7,Bangladesh,Gross Fixed Capital Formation,2023-06-30,10452.8,Yearly,BANGLADESHGROFIXCAPF,2025-05-22 03:30:00
8,Bangladesh,Gross Fixed Capital Formation,2024-06-30,10794.2,Yearly,BANGLADESHGROFIXCAPF,2025-11-13 03:53:00
9,Bangladesh,Gross Fixed Capital Formation,2025-06-30,10984.5,Yearly,BANGLADESHGROFIXCAPF,2025-11-13 03:56:00

In [21]:
gdp_per_capita = pd.read_csv("../data/tradingeconomics/GDP/GDP_per_Capita.csv")

gdp_per_capita["DateTime"] = pd.to_datetime(gdp_per_capita["DateTime"], errors='coerce')
gdp_per_capita["LastUpdate"] = pd.to_datetime(gdp_per_capita["LastUpdate"], errors='coerce')

gdp_per_capita

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP per Capita,1960-12-31,429.40,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
1,Bangladesh,GDP per Capita,1961-12-31,442.75,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
2,Bangladesh,GDP per Capita,1962-12-31,453.53,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
3,Bangladesh,GDP per Capita,1963-12-31,438.50,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
4,Bangladesh,GDP per Capita,1964-12-31,472.53,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
...,...,...,...,...,...,...,...
60,Bangladesh,GDP per Capita,2020-12-31,1604.67,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
61,Bangladesh,GDP per Capita,2021-12-31,1702.08,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
62,Bangladesh,GDP per Capita,2022-12-31,1804.35,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
63,Bangladesh,GDP per Capita,2023-12-31,1885.38,Yearly,BGDNYGDPPCAPKD,2025-02-21 07:39:00
64,Bangladesh,GDP per Capita,2024-12-31,1941.28,Yearly,BGDNYGDPPCAPKD,2025-07-01 14:51:00

In [22]:
gdp_per_capita_ppp = pd.read_csv("../data/tradingeconomics/GDP/GDP_per_Capita_PPP.csv")

gdp_per_capita_ppp["DateTime"] = pd.to_datetime(gdp_per_capita_ppp["DateTime"], errors='coerce')
gdp_per_capita_ppp["LastUpdate"] = pd.to_datetime(gdp_per_capita_ppp["LastUpdate"], errors='coerce')

gdp_per_capita_ppp

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP per Capita PPP,1990-12-31,2069.78,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
1,Bangladesh,GDP per Capita PPP,1991-12-31,2101.38,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
2,Bangladesh,GDP per Capita PPP,1992-12-31,2174.38,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
3,Bangladesh,GDP per Capita PPP,1993-12-31,2234.81,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
4,Bangladesh,GDP per Capita PPP,1994-12-31,2279.09,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
5,Bangladesh,GDP per Capita PPP,1995-12-31,2351.70,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
6,Bangladesh,GDP per Capita PPP,1996-12-31,2413.54,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
7,Bangladesh,GDP per Capita PPP,1997-12-31,2475.60,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
8,Bangladesh,GDP per Capita PPP,1998-12-31,2555.06,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
9,Bangladesh,GDP per Capita PPP,1999-12-31,2624.07,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
10,Bangladesh,GDP per Capita PPP,2000-12-31,2712.94,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
11,Bangladesh,GDP per Capita PPP,2001-12-31,2803.55,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
12,Bangladesh,GDP per Capita PPP,2002-12-31,2866.43,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
13,Bangladesh,GDP per Capita PPP,2003-12-31,2958.92,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
14,Bangladesh,GDP per Capita PPP,2004-12-31,3071.84,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
15,Bangladesh,GDP per Capita PPP,2005-12-31,3231.61,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
16,Bangladesh,GDP per Capita PPP,2006-12-31,3407.43,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
17,Bangladesh,GDP per Capita PPP,2007-12-31,3608.92,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
18,Bangladesh,GDP per Capita PPP,2008-12-31,3787.94,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
19,Bangladesh,GDP per Capita PPP,2009-12-31,3942.14,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
20,Bangladesh,GDP per Capita PPP,2010-12-31,4125.46,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
21,Bangladesh,GDP per Capita PPP,2011-12-31,4352.43,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
22,Bangladesh,GDP per Capita PPP,2012-12-31,4592.05,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
23,Bangladesh,GDP per Capita PPP,2013-12-31,4822.73,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
24,Bangladesh,GDP per Capita PPP,2014-12-31,5068.64,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
25,Bangladesh,GDP per Capita PPP,2015-12-31,5352.71,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
26,Bangladesh,GDP per Capita PPP,2016-12-31,5682.54,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
27,Bangladesh,GDP per Capita PPP,2017-12-31,6005.71,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
28,Bangladesh,GDP per Capita PPP,2018-12-31,6392.59,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
29,Bangladesh,GDP per Capita PPP,2019-12-31,6838.33,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
30,Bangladesh,GDP per Capita PPP,2020-12-31,7015.20,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
31,Bangladesh,GDP per Capita PPP,2021-12-31,7441.07,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
32,Bangladesh,GDP per Capita PPP,2022-12-31,7888.16,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
33,Bangladesh,GDP per Capita PPP,2023-12-31,8242.40,Yearly,BGDNYGDPPCAPPPCD,2025-02-24 01:17:00
34,Bangladesh,GDP per Capita PPP,2024-12-31,8486.78,Yearly,BGDNYGDPPCAPPPCD,2025-07-01 14:44:00

In [23]:
gdp_from_agriculture = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Agriculture.csv")

gdp_from_agriculture["DateTime"] = pd.to_datetime(gdp_from_agriculture["DateTime"], errors='coerce')
gdp_from_agriculture["LastUpdate"] = pd.to_datetime(gdp_from_agriculture["LastUpdate"], errors='coerce')

gdp_from_agriculture

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Agriculture,2016-06-30,2795.1,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
1,Bangladesh,GDP from Agriculture,2017-06-30,2884.4,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
2,Bangladesh,GDP from Agriculture,2018-06-30,2986.6,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
3,Bangladesh,GDP from Agriculture,2019-06-30,3084.0,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
4,Bangladesh,GDP from Agriculture,2020-06-30,3189.5,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
5,Bangladesh,GDP from Agriculture,2021-06-30,3290.8,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
6,Bangladesh,GDP from Agriculture,2022-06-30,3391.3,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
7,Bangladesh,GDP from Agriculture,2023-06-30,3505.6,Yearly,BANGLADESHGDPFROAGR,2025-05-22 03:03:00
8,Bangladesh,GDP from Agriculture,2024-06-30,3621.4,Yearly,BANGLADESHGDPFROAGR,2025-11-13 03:31:00
9,Bangladesh,GDP from Agriculture,2025-06-30,3686.3,Yearly,BANGLADESHGDPFROAGR,2025-11-13 03:31:00

In [24]:
gdp_from_construction = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Construction.csv")

gdp_from_construction["DateTime"] = pd.to_datetime(gdp_from_construction["DateTime"], errors='coerce')
gdp_from_construction["LastUpdate"] = pd.to_datetime(gdp_from_construction["LastUpdate"], errors='coerce')

gdp_from_construction

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Construction,2016-06-30,1628.4,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
1,Bangladesh,GDP from Construction,2017-06-30,1787.3,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
2,Bangladesh,GDP from Construction,2018-06-30,1967.1,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
3,Bangladesh,GDP from Construction,2019-06-30,2173.1,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
4,Bangladesh,GDP from Construction,2020-06-30,2371.5,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
5,Bangladesh,GDP from Construction,2021-06-30,2563.0,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
6,Bangladesh,GDP from Construction,2022-06-30,2786.3,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
7,Bangladesh,GDP from Construction,2023-06-30,2980.8,Yearly,BANGLADESHGDPFROCON,2025-05-22 03:09:00
8,Bangladesh,GDP from Construction,2024-06-30,3148.5,Yearly,BANGLADESHGDPFROCON,2025-11-13 03:34:00
9,Bangladesh,GDP from Construction,2025-06-30,3194.3,Yearly,BANGLADESHGDPFROCON,2025-11-13 03:34:00

In [25]:
gdp_from_manufacturing = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Manufacturing.csv")

gdp_from_manufacturing["DateTime"] = pd.to_datetime(gdp_from_manufacturing["DateTime"], errors='coerce')
gdp_from_manufacturing["LastUpdate"] = pd.to_datetime(gdp_from_manufacturing["LastUpdate"], errors='coerce')

gdp_from_manufacturing

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Manufacturing,2016-06-30,4223.9,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
1,Bangladesh,GDP from Manufacturing,2017-06-30,4523.2,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
2,Bangladesh,GDP from Manufacturing,2018-06-30,4996.0,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
3,Bangladesh,GDP from Manufacturing,2019-06-30,5612.2,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
4,Bangladesh,GDP from Manufacturing,2020-06-30,5706.5,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
5,Bangladesh,GDP from Manufacturing,2021-06-30,6367.6,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
6,Bangladesh,GDP from Manufacturing,2022-06-30,7094.2,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
7,Bangladesh,GDP from Manufacturing,2023-06-30,7725.2,Yearly,BANGLADESHGDPFROMAN,2025-05-22 03:12:00
8,Bangladesh,GDP from Manufacturing,2024-06-30,7969.1,Yearly,BANGLADESHGDPFROMAN,2025-11-13 03:37:00
9,Bangladesh,GDP from Manufacturing,2025-06-30,8421.9,Yearly,BANGLADESHGDPFROMAN,2025-11-13 03:38:00

In [26]:
gdp_from_mining = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Mining.csv")

gdp_from_mining["DateTime"] = pd.to_datetime(gdp_from_mining["DateTime"], errors='coerce')
gdp_from_mining["LastUpdate"] = pd.to_datetime(gdp_from_mining["LastUpdate"], errors='coerce')

gdp_from_mining

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Mining,2016-06-30,330.5,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
1,Bangladesh,GDP from Mining,2017-06-30,387.7,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
2,Bangladesh,GDP from Mining,2018-06-30,424.7,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
3,Bangladesh,GDP from Mining,2019-06-30,472.7,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
4,Bangladesh,GDP from Mining,2020-06-30,487.7,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
5,Bangladesh,GDP from Mining,2021-06-30,519.3,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
6,Bangladesh,GDP from Mining,2022-06-30,513.5,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
7,Bangladesh,GDP from Mining,2023-06-30,578.9,Yearly,BANGLADESHGDPFROMIN,2025-05-22 03:14:00
8,Bangladesh,GDP from Mining,2024-06-30,572.2,Yearly,BANGLADESHGDPFROMIN,2025-11-13 03:39:00
9,Bangladesh,GDP from Mining,2025-06-30,578.2,Yearly,BANGLADESHGDPFROMIN,2025-11-13 03:39:00

In [27]:
gdp_from_public_administration = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Public_Administration.csv")

gdp_from_public_administration["DateTime"] = pd.to_datetime(gdp_from_public_administration["DateTime"], errors='coerce')
gdp_from_public_administration["LastUpdate"] = pd.to_datetime(gdp_from_public_administration["LastUpdate"], errors='coerce')

gdp_from_public_administration

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Public Administration,2016-06-30,667.3,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
1,Bangladesh,GDP from Public Administration,2017-06-30,742.2,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
2,Bangladesh,GDP from Public Administration,2018-06-30,806.6,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
3,Bangladesh,GDP from Public Administration,2019-06-30,858.9,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
4,Bangladesh,GDP from Public Administration,2020-06-30,906.0,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
5,Bangladesh,GDP from Public Administration,2021-06-30,960.8,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
6,Bangladesh,GDP from Public Administration,2022-06-30,1008.0,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
7,Bangladesh,GDP from Public Administration,2023-06-30,1078.9,Yearly,BANGLADESHGFPA,2025-05-22 03:17:00
8,Bangladesh,GDP from Public Administration,2024-06-30,1139.1,Yearly,BANGLADESHGFPA,2025-11-13 03:40:00
9,Bangladesh,GDP from Public Administration,2025-06-30,1214.3,Yearly,BANGLADESHGFPA,2025-11-13 03:40:00

In [28]:
gdp_from_services = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Services.csv")

gdp_from_services["DateTime"] = pd.to_datetime(gdp_from_services["DateTime"], errors='coerce')
gdp_from_services["LastUpdate"] = pd.to_datetime(gdp_from_services["LastUpdate"], errors='coerce')

gdp_from_services

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Services,2016-06-30,10629.8,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
1,Bangladesh,GDP from Services,2017-06-30,11307.5,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
2,Bangladesh,GDP from Services,2018-06-30,12048.5,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
3,Bangladesh,GDP from Services,2019-06-30,12877.4,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
4,Bangladesh,GDP from Services,2020-06-30,13383.9,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
5,Bangladesh,GDP from Services,2021-06-30,14151.1,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
6,Bangladesh,GDP from Services,2022-06-30,15036.5,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
7,Bangladesh,GDP from Services,2023-06-30,15844.1,Yearly,BANGLADESHGDPFROSER,2025-05-22 03:19:00
8,Bangladesh,GDP from Services,2024-06-30,16650.5,Yearly,BANGLADESHGDPFROSER,2025-11-13 03:46:00
9,Bangladesh,GDP from Services,2025-06-30,17400.8,Yearly,BANGLADESHGDPFROSER,2025-11-13 03:46:00

In [29]:
gdp_from_transport = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_Transport.csv")

gdp_from_transport["DateTime"] = pd.to_datetime(gdp_from_transport["DateTime"], errors='coerce')
gdp_from_transport["LastUpdate"] = pd.to_datetime(gdp_from_transport["LastUpdate"], errors='coerce')

gdp_from_transport

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Transport,2016-06-30,1580.3,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
1,Bangladesh,GDP from Transport,2017-06-30,1677.1,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
2,Bangladesh,GDP from Transport,2018-06-30,1790.1,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
3,Bangladesh,GDP from Transport,2019-06-30,1915.6,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
4,Bangladesh,GDP from Transport,2020-06-30,1948.7,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
5,Bangladesh,GDP from Transport,2021-06-30,2027.4,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
6,Bangladesh,GDP from Transport,2022-06-30,2144.0,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
7,Bangladesh,GDP from Transport,2023-06-30,2261.6,Yearly,BANGLADESHGDPFROTRA,2025-05-22 03:21:00
8,Bangladesh,GDP from Transport,2024-06-30,2377.9,Yearly,BANGLADESHGDPFROTRA,2025-11-13 03:48:00
9,Bangladesh,GDP from Transport,2025-06-30,2481.8,Yearly,BANGLADESHGDPFROTRA,2025-11-13 03:48:00

In [30]:
gdp_from_utilities = pd.read_csv("../data/tradingeconomics/GDP/GDP_from_utilities.csv")

gdp_from_utilities["DateTime"] = pd.to_datetime(gdp_from_utilities["DateTime"], errors='coerce')
gdp_from_utilities["LastUpdate"] = pd.to_datetime(gdp_from_utilities["LastUpdate"], errors='coerce')

gdp_from_utilities

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP from Utilities,2016-06-30,245.5,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
1,Bangladesh,GDP from Utilities,2017-06-30,262.9,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
2,Bangladesh,GDP from Utilities,2018-06-30,284.7,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
3,Bangladesh,GDP from Utilities,2019-06-30,308.1,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
4,Bangladesh,GDP from Utilities,2020-06-30,310.2,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
5,Bangladesh,GDP from Utilities,2021-06-30,339.8,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
6,Bangladesh,GDP from Utilities,2022-06-30,360.7,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
7,Bangladesh,GDP from Utilities,2023-06-30,369.6,Yearly,BANGLADESHGDPFROUTI,2025-05-22 03:24:00
8,Bangladesh,GDP from Utilities,2024-06-30,373.2,Yearly,BANGLADESHGDPFROUTI,2025-11-13 03:51:00
9,Bangladesh,GDP from Utilities,2025-06-30,391.1,Yearly,BANGLADESHGDPFROUTI,2025-11-13 04:11:00

<br> <br> 

## Labor

In [31]:
unemployment_rate = pd.read_csv("../data/tradingeconomics/Labor/Unemployment_Rate.csv")

unemployment_rate["DateTime"] = pd.to_datetime(unemployment_rate["DateTime"], errors='coerce')
unemployment_rate["LastUpdate"] = pd.to_datetime(unemployment_rate["LastUpdate"], errors='coerce')

unemployment_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Unemployment Rate,1991-12-31,2.2,Yearly,BangladeshUR,2017-06-06 11:46:00
1,Bangladesh,Unemployment Rate,1992-12-31,2.3,Yearly,BangladeshUR,2024-02-06 02:39:00
2,Bangladesh,Unemployment Rate,1993-12-31,2.3,Yearly,BangladeshUR,2024-02-06 02:39:00
3,Bangladesh,Unemployment Rate,1994-12-31,2.4,Yearly,BangladeshUR,2024-02-06 02:39:00
4,Bangladesh,Unemployment Rate,1995-12-31,2.4,Yearly,BangladeshUR,2024-02-06 02:39:00
5,Bangladesh,Unemployment Rate,1996-12-31,2.5,Yearly,BangladeshUR,2017-06-06 11:46:00
6,Bangladesh,Unemployment Rate,1997-12-31,2.7,Yearly,BangladeshUR,2024-02-06 02:39:00
7,Bangladesh,Unemployment Rate,1998-12-31,2.9,Yearly,BangladeshUR,2024-02-06 02:39:00
8,Bangladesh,Unemployment Rate,1999-12-31,3.1,Yearly,BangladeshUR,2024-02-06 02:39:00
9,Bangladesh,Unemployment Rate,2000-12-31,3.3,Yearly,BangladeshUR,2017-06-06 11:46:00
10,Bangladesh,Unemployment Rate,2001-12-31,3.6,Yearly,BangladeshUR,2024-02-06 02:39:00
11,Bangladesh,Unemployment Rate,2002-12-31,4.0,Yearly,BangladeshUR,2024-02-06 02:39:00
12,Bangladesh,Unemployment Rate,2003-12-31,4.3,Yearly,BangladeshUR,2012-04-03 18:06:00
13,Bangladesh,Unemployment Rate,2004-12-31,4.3,Yearly,BangladeshUR,2024-02-06 02:39:00
14,Bangladesh,Unemployment Rate,2005-12-31,4.3,Yearly,BangladeshUR,2017-06-06 11:46:00
15,Bangladesh,Unemployment Rate,2006-12-31,3.6,Yearly,BangladeshUR,2024-02-06 02:39:00
16,Bangladesh,Unemployment Rate,2007-12-31,4.1,Yearly,BangladeshUR,2024-02-06 02:39:00
17,Bangladesh,Unemployment Rate,2008-12-31,4.5,Yearly,BangladeshUR,2024-02-06 02:39:00
18,Bangladesh,Unemployment Rate,2009-12-31,5.0,Yearly,BangladeshUR,2017-06-06 11:46:00
19,Bangladesh,Unemployment Rate,2010-12-31,3.4,Yearly,BangladeshUR,2024-02-06 02:39:00
20,Bangladesh,Unemployment Rate,2011-12-31,3.7,Yearly,BangladeshUR,2024-02-06 02:39:00
21,Bangladesh,Unemployment Rate,2012-12-31,4.1,Yearly,BangladeshUR,2024-02-06 02:39:00
22,Bangladesh,Unemployment Rate,2013-12-31,4.4,Yearly,BangladeshUR,2024-02-06 02:39:00
23,Bangladesh,Unemployment Rate,2014-12-31,4.4,Yearly,BangladeshUR,2024-02-06 02:39:00
24,Bangladesh,Unemployment Rate,2015-12-31,4.4,Yearly,BangladeshUR,2024-02-06 02:39:00
25,Bangladesh,Unemployment Rate,2016-12-31,4.4,Yearly,BangladeshUR,2024-02-06 02:39:00
26,Bangladesh,Unemployment Rate,2017-12-31,4.4,Yearly,BangladeshUR,2024-02-06 02:39:00
27,Bangladesh,Unemployment Rate,2018-12-31,4.4,Yearly,BangladeshUR,2023-05-24 08:31:00
28,Bangladesh,Unemployment Rate,2019-12-31,4.4,Yearly,BangladeshUR,2023-05-24 08:31:00
29,Bangladesh,Unemployment Rate,2020-12-31,5.3,Yearly,BangladeshUR,2024-02-06 02:39:00
30,Bangladesh,Unemployment Rate,2021-12-31,5.2,Yearly,BangladeshUR,2024-02-06 02:39:00
31,Bangladesh,Unemployment Rate,2022-12-31,4.3,Yearly,BangladeshUR,2024-02-06 02:39:00
32,Bangladesh,Unemployment Rate,2023-12-31,4.2,Yearly,BangladeshUR,2024-02-06 02:39:00
33,Bangladesh,Unemployment Rate,2024-12-31,4.7,Yearly,BangladeshUR,2025-05-15 10:23:00

In [32]:
population = pd.read_csv("../data/tradingeconomics/Labor/Population.csv")

population["DateTime"] = pd.to_datetime(population["DateTime"], errors='coerce')
population["LastUpdate"] = pd.to_datetime(population["LastUpdate"], errors='coerce')

population

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Population,1960-12-31,50.10,Yearly,BGD SP.POP.TOTL,2015-07-15 11:05:00
1,Bangladesh,Population,1961-12-31,51.53,Yearly,BGD SP.POP.TOTL,2015-07-15 11:05:00
2,Bangladesh,Population,1962-12-31,52.98,Yearly,BGD SP.POP.TOTL,2015-07-15 11:05:00
3,Bangladesh,Population,1963-12-31,54.47,Yearly,BGD SP.POP.TOTL,2015-07-15 11:05:00
4,Bangladesh,Population,1964-12-31,56.07,Yearly,BGD SP.POP.TOTL,2015-07-15 11:05:00
...,...,...,...,...,...,...,...
60,Bangladesh,Population,2020-12-31,166.30,Yearly,BGD SP.POP.TOTL,2025-03-06 06:15:00
61,Bangladesh,Population,2021-12-31,167.70,Yearly,BGD SP.POP.TOTL,2025-03-06 06:16:00
62,Bangladesh,Population,2022-12-31,169.40,Yearly,BGD SP.POP.TOTL,2025-03-06 06:16:00
63,Bangladesh,Population,2023-12-31,171.50,Yearly,BGD SP.POP.TOTL,2025-05-26 06:54:00
64,Bangladesh,Population,2024-12-31,171.60,Yearly,BGD SP.POP.TOTL,2025-05-26 06:51:00

In [33]:
minimum_wages = pd.read_csv("../data/tradingeconomics/Labor/Minimum_Wages.csv")

minimum_wages["DateTime"] = pd.to_datetime(minimum_wages["DateTime"], errors='coerce')
minimum_wages["LastUpdate"] = pd.to_datetime(minimum_wages["LastUpdate"], errors='coerce')

minimum_wages

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Minimum Wages,2014-12-31,5300,Yearly,BANGLADESHMINWAG,2018-02-09 14:20:00
1,Bangladesh,Minimum Wages,2015-12-31,5300,Yearly,BANGLADESHMINWAG,2018-02-09 14:20:00
2,Bangladesh,Minimum Wages,2016-12-31,5300,Yearly,BANGLADESHMINWAG,2018-02-09 14:20:00
3,Bangladesh,Minimum Wages,2017-12-31,5300,Yearly,BANGLADESHMINWAG,2018-02-09 14:19:00
4,Bangladesh,Minimum Wages,2018-12-31,5300,Yearly,BANGLADESHMINWAG,2018-08-20 15:41:00
5,Bangladesh,Minimum Wages,2019-12-31,8000,Yearly,BANGLADESHMINWAG,2019-01-13 18:55:00
6,Bangladesh,Minimum Wages,2020-12-31,8000,Yearly,BANGLADESHMINWAG,2023-09-14 09:15:00
7,Bangladesh,Minimum Wages,2021-12-31,8000,Yearly,BANGLADESHMINWAG,2022-06-30 13:24:00
8,Bangladesh,Minimum Wages,2022-12-31,8000,Yearly,BANGLADESHMINWAG,2022-06-30 13:24:00
9,Bangladesh,Minimum Wages,2023-12-01,12500,Yearly,BANGLADESHMINWAG,2024-01-10 05:55:00
10,Bangladesh,Minimum Wages,2024-12-31,12500,Yearly,BANGLADESHMINWAG,2024-01-10 05:55:00
11,Bangladesh,Minimum Wages,2025-12-31,12500,Yearly,BANGLADESHMINWAG,2025-05-28 02:11:00

In [34]:
retirement_age_men = pd.read_csv("../data/tradingeconomics/Labor/Retirement_Age_Men.csv")

retirement_age_men["DateTime"] = pd.to_datetime(retirement_age_men["DateTime"], errors='coerce')
retirement_age_men["LastUpdate"] = pd.to_datetime(retirement_age_men["LastUpdate"], errors='coerce')

retirement_age_men

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Retirement Age Men,2011-12-31,57,Yearly,BANGLADESHRETAGEMEN,2015-09-03 18:27:00
1,Bangladesh,Retirement Age Men,2012-12-31,59,Yearly,BANGLADESHRETAGEMEN,2015-09-03 18:27:00
2,Bangladesh,Retirement Age Men,2013-12-31,59,Yearly,BANGLADESHRETAGEMEN,2015-09-03 18:27:00
3,Bangladesh,Retirement Age Men,2014-12-31,59,Yearly,BANGLADESHRETAGEMEN,2015-09-03 18:27:00
4,Bangladesh,Retirement Age Men,2015-12-31,59,Yearly,BANGLADESHRETAGEMEN,2015-09-03 18:26:00
5,Bangladesh,Retirement Age Men,2016-12-31,59,Yearly,BANGLADESHRETAGEMEN,2017-01-04 16:33:00
6,Bangladesh,Retirement Age Men,2017-12-31,59,Yearly,BANGLADESHRETAGEMEN,2017-02-20 10:04:00
7,Bangladesh,Retirement Age Men,2018-12-31,59,Yearly,BANGLADESHRETAGEMEN,2018-03-07 12:46:00
8,Bangladesh,Retirement Age Men,2019-12-31,59,Yearly,BANGLADESHRETAGEMEN,2020-04-30 21:07:00
9,Bangladesh,Retirement Age Men,2020-12-31,59,Yearly,BANGLADESHRETAGEMEN,2021-03-02 14:35:00
10,Bangladesh,Retirement Age Men,2021-12-31,59,Yearly,BANGLADESHRETAGEMEN,2022-09-26 05:51:00
11,Bangladesh,Retirement Age Men,2022-12-31,59,Yearly,BANGLADESHRETAGEMEN,2022-09-27 03:22:00
12,Bangladesh,Retirement Age Men,2023-12-31,59,Yearly,BANGLADESHRETAGEMEN,2023-10-24 00:24:00
13,Bangladesh,Retirement Age Men,2024-12-31,59,Yearly,BANGLADESHRETAGEMEN,2024-01-15 07:50:00
14,Bangladesh,Retirement Age Men,2025-12-31,59,Yearly,BANGLADESHRETAGEMEN,2025-01-27 07:36:00

In [35]:
retirement_age_women = pd.read_csv("../data/tradingeconomics/Labor/Retirement_Age_Women.csv")

retirement_age_women["DateTime"] = pd.to_datetime(retirement_age_women["DateTime"], errors='coerce')
retirement_age_women["LastUpdate"] = pd.to_datetime(retirement_age_women["LastUpdate"], errors='coerce')

retirement_age_women

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Retirement Age Women,2011-12-31,57,Yearly,BANGLADESHRETAGEWOM,2015-09-03 18:31:00
1,Bangladesh,Retirement Age Women,2012-12-31,59,Yearly,BANGLADESHRETAGEWOM,2015-09-03 18:31:00
2,Bangladesh,Retirement Age Women,2013-12-31,59,Yearly,BANGLADESHRETAGEWOM,2015-09-03 18:31:00
3,Bangladesh,Retirement Age Women,2014-12-31,59,Yearly,BANGLADESHRETAGEWOM,2015-09-03 18:31:00
4,Bangladesh,Retirement Age Women,2015-12-31,59,Yearly,BANGLADESHRETAGEWOM,2015-09-03 18:31:00
5,Bangladesh,Retirement Age Women,2016-12-31,59,Yearly,BANGLADESHRETAGEWOM,2017-01-04 16:34:00
6,Bangladesh,Retirement Age Women,2017-12-31,59,Yearly,BANGLADESHRETAGEWOM,2017-02-20 10:05:00
7,Bangladesh,Retirement Age Women,2018-12-31,59,Yearly,BANGLADESHRETAGEWOM,2018-03-07 12:46:00
8,Bangladesh,Retirement Age Women,2019-12-31,59,Yearly,BANGLADESHRETAGEWOM,2020-04-30 21:07:00
9,Bangladesh,Retirement Age Women,2020-12-31,59,Yearly,BANGLADESHRETAGEWOM,2021-03-02 14:36:00
10,Bangladesh,Retirement Age Women,2021-12-31,59,Yearly,BANGLADESHRETAGEWOM,2022-09-26 05:57:00
11,Bangladesh,Retirement Age Women,2022-12-31,59,Yearly,BANGLADESHRETAGEWOM,2022-09-27 03:25:00
12,Bangladesh,Retirement Age Women,2023-12-31,59,Yearly,BANGLADESHRETAGEWOM,2023-10-24 00:29:00
13,Bangladesh,Retirement Age Women,2024-12-31,59,Yearly,BANGLADESHRETAGEWOM,2024-01-15 07:51:00
14,Bangladesh,Retirement Age Women,2025-12-31,59,Yearly,BANGLADESHRETAGEWOM,2025-01-27 07:36:00

<br> <br> 

## Prices

In [36]:
inflation_rate = pd.read_csv("../data/tradingeconomics/Prices/Inflation_Rate.csv")

inflation_rate["DateTime"] = pd.to_datetime(inflation_rate["DateTime"], errors='coerce')
inflation_rate["LastUpdate"] = pd.to_datetime(inflation_rate["LastUpdate"], errors='coerce')

inflation_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Inflation Rate,1994-07-31,5.50,Monthly,BangladeshIR,2016-04-05 14:51:00
1,Bangladesh,Inflation Rate,1994-08-31,7.11,Monthly,BangladeshIR,2016-04-05 14:51:00
2,Bangladesh,Inflation Rate,1994-09-30,6.84,Monthly,BangladeshIR,2016-04-05 14:51:00
3,Bangladesh,Inflation Rate,1994-10-31,8.30,Monthly,BangladeshIR,2016-04-05 14:51:00
4,Bangladesh,Inflation Rate,1994-11-30,7.62,Monthly,BangladeshIR,2016-04-05 14:51:00
...,...,...,...,...,...,...,...
375,Bangladesh,Inflation Rate,2025-08-31,8.29,Monthly,BangladeshIR,2025-09-09 03:03:00
376,Bangladesh,Inflation Rate,2025-09-30,8.36,Monthly,BangladeshIR,2025-10-09 06:46:00
377,Bangladesh,Inflation Rate,2025-10-31,8.17,Monthly,BangladeshIR,2025-11-09 03:48:00
378,Bangladesh,Inflation Rate,2025-11-30,8.29,Monthly,BangladeshIR,2025-12-08 00:16:00
379,Bangladesh,Inflation Rate,2025-12-31,8.49,Monthly,BangladeshIR,2026-01-13 03:21:00

In [37]:
consumer_price_index_cpi = pd.read_csv("../data/tradingeconomics/Prices/Consumer_Price_Index_CPI.csv")

consumer_price_index_cpi["DateTime"] = pd.to_datetime(consumer_price_index_cpi["DateTime"], errors='coerce')
consumer_price_index_cpi["LastUpdate"] = pd.to_datetime(consumer_price_index_cpi["LastUpdate"], errors='coerce')

consumer_price_index_cpi

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Consumer Price Index CPI,2011-05-31,52.53,Monthly,BANGLADESHCONPRIINDC,2023-05-23 13:18:00
1,Bangladesh,Consumer Price Index CPI,2011-06-30,53.04,Monthly,BANGLADESHCONPRIINDC,2023-05-23 13:18:00
2,Bangladesh,Consumer Price Index CPI,2011-07-31,54.11,Monthly,BANGLADESHCONPRIINDC,2023-05-23 13:18:00
3,Bangladesh,Consumer Price Index CPI,2011-08-31,55.24,Monthly,BANGLADESHCONPRIINDC,2023-05-23 13:18:00
4,Bangladesh,Consumer Price Index CPI,2011-09-30,56.19,Monthly,BANGLADESHCONPRIINDC,2023-05-23 13:18:00
...,...,...,...,...,...,...,...
171,Bangladesh,Consumer Price Index CPI,2025-08-31,140.06,Monthly,BANGLADESHCONPRIINDC,2025-09-09 02:55:00
172,Bangladesh,Consumer Price Index CPI,2025-09-30,141.53,Monthly,BANGLADESHCONPRIINDC,2025-10-09 06:46:00
173,Bangladesh,Consumer Price Index CPI,2025-10-31,144.21,Monthly,BANGLADESHCONPRIINDC,2025-11-09 03:56:00
174,Bangladesh,Consumer Price Index CPI,2025-11-30,143.65,Monthly,BANGLADESHCONPRIINDC,2025-12-08 00:18:00
175,Bangladesh,Consumer Price Index CPI,2025-12-31,142.44,Monthly,BANGLADESHCONPRIINDC,2026-01-13 03:22:00

In [38]:
gdp_deflator = pd.read_csv("../data/tradingeconomics/Prices/GDP_Deflator.csv")

gdp_deflator["DateTime"] = pd.to_datetime(gdp_deflator["DateTime"], errors='coerce')
gdp_deflator["LastUpdate"] = pd.to_datetime(gdp_deflator["LastUpdate"], errors='coerce')

gdp_deflator

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,GDP Deflator,2003-06-30,126.35,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
1,Bangladesh,GDP Deflator,2004-06-30,132.93,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
2,Bangladesh,GDP Deflator,2005-06-30,138.78,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
3,Bangladesh,GDP Deflator,2006-06-30,146.07,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
4,Bangladesh,GDP Deflator,2007-06-30,155.95,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
5,Bangladesh,GDP Deflator,2008-06-30,168.41,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
6,Bangladesh,GDP Deflator,2009-06-30,180.72,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
7,Bangladesh,GDP Deflator,2010-06-30,192.42,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
8,Bangladesh,GDP Deflator,2011-06-30,206.91,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
9,Bangladesh,GDP Deflator,2012-06-30,224.46,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
10,Bangladesh,GDP Deflator,2013-06-30,164.26,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
11,Bangladesh,GDP Deflator,2014-06-30,173.57,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
12,Bangladesh,GDP Deflator,2015-06-30,183.76,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
13,Bangladesh,GDP Deflator,2016-06-30,196.13,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
14,Bangladesh,GDP Deflator,2017-06-30,208.44,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
15,Bangladesh,GDP Deflator,2018-06-30,220.11,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
16,Bangladesh,GDP Deflator,2019-06-30,115.21,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
17,Bangladesh,GDP Deflator,2020-06-30,119.64,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
18,Bangladesh,GDP Deflator,2021-06-30,124.57,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
19,Bangladesh,GDP Deflator,2022-06-30,130.86,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
20,Bangladesh,GDP Deflator,2023-06-30,139.88,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
21,Bangladesh,GDP Deflator,2024-06-30,149.51,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00
22,Bangladesh,GDP Deflator,2025-06-30,159.61,Yearly,BANGLADESHGDPDEF,2025-11-13 08:23:00

In [39]:
cpi_transportation = pd.read_csv("../data/tradingeconomics/Prices/CPI_Transportation.csv")

cpi_transportation["DateTime"] = pd.to_datetime(cpi_transportation["DateTime"], errors='coerce')
cpi_transportation["LastUpdate"] = pd.to_datetime(cpi_transportation["LastUpdate"], errors='coerce')

cpi_transportation

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,CPI Transportation,2023-04-30,110.11,Monthly,BANGLADESHCPITRA,2023-07-06 01:55:00
1,Bangladesh,CPI Transportation,2023-05-31,110.38,Monthly,BANGLADESHCPITRA,2023-07-06 01:55:00
2,Bangladesh,CPI Transportation,2023-06-30,110.52,Monthly,BANGLADESHCPITRA,2023-07-06 01:56:00
3,Bangladesh,CPI Transportation,2023-07-31,110.64,Monthly,BANGLADESHCPITRA,2023-08-10 04:16:00
4,Bangladesh,CPI Transportation,2023-08-31,115.73,Monthly,BANGLADESHCPITRA,2023-09-21 15:24:00
5,Bangladesh,CPI Transportation,2023-09-30,116.20,Monthly,BANGLADESHCPITRA,2023-10-16 04:02:00
6,Bangladesh,CPI Transportation,2023-10-31,117.22,Monthly,BANGLADESHCPITRA,2023-11-08 09:00:00
7,Bangladesh,CPI Transportation,2023-11-30,117.85,Monthly,BANGLADESHCPITRA,2023-12-20 11:40:00
8,Bangladesh,CPI Transportation,2023-12-31,118.05,Monthly,BANGLADESHCPITRA,2024-01-15 13:25:00
9,Bangladesh,CPI Transportation,2024-01-31,119.21,Monthly,BANGLADESHCPITRA,2024-02-16 01:23:00
10,Bangladesh,CPI Transportation,2024-02-29,119.31,Monthly,BANGLADESHCPITRA,2024-03-14 10:56:00
11,Bangladesh,CPI Transportation,2024-03-31,119.20,Monthly,BANGLADESHCPITRA,2024-04-22 09:40:00
12,Bangladesh,CPI Transportation,2024-04-30,119.17,Monthly,BANGLADESHCPITRA,2024-05-14 05:47:00
13,Bangladesh,CPI Transportation,2024-05-31,119.33,Monthly,BANGLADESHCPITRA,2024-06-10 08:42:00
14,Bangladesh,CPI Transportation,2024-06-30,119.48,Monthly,BANGLADESHCPITRA,2024-07-10 04:05:00
15,Bangladesh,CPI Transportation,2024-07-31,119.79,Monthly,BANGLADESHCPITRA,2024-08-14 08:19:00
16,Bangladesh,CPI Transportation,2024-08-31,120.70,Monthly,BANGLADESHCPITRA,2024-09-16 02:18:00
17,Bangladesh,CPI Transportation,2024-09-30,123.37,Monthly,BANGLADESHCPITRA,2024-10-13 04:20:00
18,Bangladesh,CPI Transportation,2024-10-31,123.83,Monthly,BANGLADESHCPITRA,2024-11-14 01:17:00
19,Bangladesh,CPI Transportation,2024-11-30,124.51,Monthly,BANGLADESHCPITRA,2024-12-11 04:33:00
20,Bangladesh,CPI Transportation,2024-12-31,125.23,Monthly,BANGLADESHCPITRA,2025-01-15 03:34:00
21,Bangladesh,CPI Transportation,2025-01-31,126.43,Monthly,BANGLADESHCPITRA,2025-02-07 04:10:00
22,Bangladesh,CPI Transportation,2025-02-28,126.64,Monthly,BANGLADESHCPITRA,2025-03-07 04:09:00
23,Bangladesh,CPI Transportation,2025-03-31,127.17,Monthly,BANGLADESHCPITRA,2025-04-09 03:19:00
24,Bangladesh,CPI Transportation,2025-04-30,127.32,Monthly,BANGLADESHCPITRA,2025-05-13 03:18:00
25,Bangladesh,CPI Transportation,2025-05-31,127.26,Monthly,BANGLADESHCPITRA,2025-06-09 02:05:00
26,Bangladesh,CPI Transportation,2025-06-30,127.16,Monthly,BANGLADESHCPITRA,2025-07-07 23:51:00
27,Bangladesh,CPI Transportation,2025-07-31,128.28,Monthly,BANGLADESHCPITRA,2025-08-08 02:28:00
28,Bangladesh,CPI Transportation,2025-08-31,128.86,Monthly,BANGLADESHCPITRA,2025-09-09 02:59:00
29,Bangladesh,CPI Transportation,2025-09-30,131.15,Monthly,BANGLADESHCPITRA,2025-10-09 06:47:00
30,Bangladesh,CPI Transportation,2025-10-31,132.25,Monthly,BANGLADESHCPITRA,2025-11-09 04:05:00
31,Bangladesh,CPI Transportation,2025-11-30,133.70,Monthly,BANGLADESHCPITRA,2025-12-08 00:19:00
32,Bangladesh,CPI Transportation,2025-12-31,134.34,Monthly,BANGLADESHCPITRA,2026-01-13 03:22:00

In [40]:
food_inflation = pd.read_csv("../data/tradingeconomics/Prices/Food_Inflation.csv")

food_inflation["DateTime"] = pd.to_datetime(food_inflation["DateTime"], errors='coerce')
food_inflation["LastUpdate"] = pd.to_datetime(food_inflation["LastUpdate"], errors='coerce')

food_inflation

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Food Inflation,2013-04-30,8.68,Monthly,BANGLADESHFOOINF,2014-06-30 13:29:00
1,Bangladesh,Food Inflation,2013-05-31,8.13,Monthly,BANGLADESHFOOINF,2014-06-30 13:29:00
2,Bangladesh,Food Inflation,2013-06-30,8.26,Monthly,BANGLADESHFOOINF,2014-07-15 17:18:00
3,Bangladesh,Food Inflation,2013-07-31,8.09,Monthly,BANGLADESHFOOINF,2014-06-30 13:29:00
4,Bangladesh,Food Inflation,2013-08-31,7.93,Monthly,BANGLADESHFOOINF,2014-06-30 13:29:00
...,...,...,...,...,...,...,...
147,Bangladesh,Food Inflation,2025-08-31,7.60,Monthly,BANGLADESHFOOINF,2025-09-09 02:57:00
148,Bangladesh,Food Inflation,2025-09-30,7.64,Monthly,BANGLADESHFOOINF,2025-10-09 06:47:00
149,Bangladesh,Food Inflation,2025-10-31,7.08,Monthly,BANGLADESHFOOINF,2025-11-09 04:07:00
150,Bangladesh,Food Inflation,2025-11-30,7.36,Monthly,BANGLADESHFOOINF,2025-12-08 00:19:00
151,Bangladesh,Food Inflation,2025-12-31,7.71,Monthly,BANGLADESHFOOINF,2026-01-13 03:23:00

In [41]:
inflation_rate_mom = pd.read_csv("../data/tradingeconomics/Prices/Inflation_Rate_MoM.csv")

inflation_rate_mom["DateTime"] = pd.to_datetime(inflation_rate_mom["DateTime"], errors='coerce')
inflation_rate_mom["LastUpdate"] = pd.to_datetime(inflation_rate_mom["LastUpdate"], errors='coerce')

inflation_rate_mom

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Inflation Rate MoM,2011-06-30,0.98,Monthly,BANGLADESHINFRATMOM,2014-08-26 14:42:00
1,Bangladesh,Inflation Rate MoM,2011-07-31,2.01,Monthly,BANGLADESHINFRATMOM,2014-08-26 14:42:00
2,Bangladesh,Inflation Rate MoM,2011-08-31,2.08,Monthly,BANGLADESHINFRATMOM,2014-08-26 14:42:00
3,Bangladesh,Inflation Rate MoM,2011-09-30,1.72,Monthly,BANGLADESHINFRATMOM,2014-08-26 14:42:00
4,Bangladesh,Inflation Rate MoM,2011-10-31,0.15,Monthly,BANGLADESHINFRATMOM,2014-08-26 14:42:00
...,...,...,...,...,...,...,...
169,Bangladesh,Inflation Rate MoM,2025-08-31,2.36,Monthly,BANGLADESHINFRATMOM,2025-09-09 03:04:00
170,Bangladesh,Inflation Rate MoM,2025-09-30,1.05,Monthly,BANGLADESHINFRATMOM,2025-10-09 06:46:00
171,Bangladesh,Inflation Rate MoM,2025-10-31,1.89,Monthly,BANGLADESHINFRATMOM,2025-11-09 04:00:00
172,Bangladesh,Inflation Rate MoM,2025-11-30,-0.39,Monthly,BANGLADESHINFRATMOM,2025-12-08 00:16:00
173,Bangladesh,Inflation Rate MoM,2025-12-31,-0.84,Monthly,BANGLADESHINFRATMOM,2026-01-13 03:21:00

<br> <br> 

## Money

In [42]:
interest_rate = pd.read_csv("../data/tradingeconomics/Money/Interest_Rate.csv")

interest_rate["DateTime"] = pd.to_datetime(interest_rate["DateTime"], errors='coerce')
interest_rate["LastUpdate"] = pd.to_datetime(interest_rate["LastUpdate"], errors='coerce')

interest_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Interest Rate,2008-01-31,8.5,Daily,BangladeshIntRate,2011-06-27 00:00:00
1,Bangladesh,Interest Rate,2008-02-29,8.5,Daily,BangladeshIntRate,2011-06-27 00:00:00
2,Bangladesh,Interest Rate,2008-03-31,8.5,Daily,BangladeshIntRate,2011-06-27 00:00:00
3,Bangladesh,Interest Rate,2008-04-30,8.5,Daily,BangladeshIntRate,2011-06-27 00:00:00
4,Bangladesh,Interest Rate,2008-05-31,8.5,Daily,BangladeshIntRate,2011-06-27 00:00:00
...,...,...,...,...,...,...,...
211,Bangladesh,Interest Rate,2025-08-31,10.0,Daily,BangladeshIntRate,2025-09-02 07:19:00
212,Bangladesh,Interest Rate,2025-09-30,10.0,Daily,BangladeshIntRate,2025-10-02 02:45:00
213,Bangladesh,Interest Rate,2025-10-31,10.0,Daily,BangladeshIntRate,2025-11-04 10:28:00
214,Bangladesh,Interest Rate,2025-11-30,10.0,Daily,BangladeshIntRate,2025-12-04 04:30:00
215,Bangladesh,Interest Rate,2025-12-31,10.0,Daily,BangladeshIntRate,2025-12-05 03:32:00

In [43]:
interbank_rate = pd.read_csv("../data/tradingeconomics/Money/Interbank_Rate.csv")

interbank_rate["DateTime"] = pd.to_datetime(interbank_rate["DateTime"], errors='coerce')
interbank_rate["LastUpdate"] = pd.to_datetime(interbank_rate["LastUpdate"], errors='coerce')

interbank_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Interbank Rate,1997-01-31,5.87,Monthly,BANGLADESHINTRAT,2015-04-30 13:11:00
1,Bangladesh,Interbank Rate,1997-02-28,7.63,Monthly,BANGLADESHINTRAT,2015-04-30 13:11:00
2,Bangladesh,Interbank Rate,1997-03-31,6.97,Monthly,BANGLADESHINTRAT,2015-04-30 13:11:00
3,Bangladesh,Interbank Rate,1997-04-30,8.94,Monthly,BANGLADESHINTRAT,2015-04-30 13:11:00
4,Bangladesh,Interbank Rate,1997-05-30,8.46,Monthly,BANGLADESHINTRAT,2015-04-30 13:11:00
...,...,...,...,...,...,...,...
343,Bangladesh,Interbank Rate,2025-08-31,9.98,Monthly,BANGLADESHINTRAT,2025-09-25 03:15:00
344,Bangladesh,Interbank Rate,2025-09-30,9.97,Monthly,BANGLADESHINTRAT,2025-10-15 09:17:00
345,Bangladesh,Interbank Rate,2025-10-31,9.74,Monthly,BANGLADESHINTRAT,2025-11-24 00:07:00
346,Bangladesh,Interbank Rate,2025-11-30,9.79,Monthly,BANGLADESHINTRAT,2025-12-11 02:17:00
347,Bangladesh,Interbank Rate,2025-12-31,9.99,Monthly,BANGLADESHINTRAT,2026-01-12 03:27:00

In [44]:
money_supply_m0 = pd.read_csv("../data/tradingeconomics/Money/Money_Supply_M0.csv")

money_supply_m0["DateTime"] = pd.to_datetime(money_supply_m0["DateTime"], errors='coerce')
money_supply_m0["LastUpdate"] = pd.to_datetime(money_supply_m0["LastUpdate"], errors='coerce')

money_supply_m0

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Money Supply M0,1990-07-31,35.93,Monthly,BANGLADESHMONSUPM0,2014-11-16 21:32:00
1,Bangladesh,Money Supply M0,1990-08-31,35.13,Monthly,BANGLADESHMONSUPM0,2012-09-28 19:03:00
2,Bangladesh,Money Supply M0,1990-09-30,35.26,Monthly,BANGLADESHMONSUPM0,2014-11-16 21:32:00
3,Bangladesh,Money Supply M0,1990-10-31,34.50,Monthly,BANGLADESHMONSUPM0,2014-11-16 21:32:00
4,Bangladesh,Money Supply M0,1990-11-30,34.38,Monthly,BANGLADESHMONSUPM0,2012-09-28 19:03:00
...,...,...,...,...,...,...,...
418,Bangladesh,Money Supply M0,2025-06-30,3266.97,Monthly,BANGLADESHMONSUPM0,2025-08-26 04:37:00
419,Bangladesh,Money Supply M0,2025-07-31,3153.10,Monthly,BANGLADESHMONSUPM0,2025-09-25 03:08:00
420,Bangladesh,Money Supply M0,2025-08-31,3069.96,Monthly,BANGLADESHMONSUPM0,2025-10-29 05:05:00
421,Bangladesh,Money Supply M0,2025-09-30,3034.86,Monthly,BANGLADESHMONSUPM0,2025-12-05 04:07:00
422,Bangladesh,Money Supply M0,2025-10-31,2987.60,Monthly,BANGLADESHMONSUPM0,2026-01-05 06:11:00

In [45]:
money_supply_m1 = pd.read_csv("../data/tradingeconomics/Money/Money_Supply_M1.csv")

money_supply_m1["DateTime"] = pd.to_datetime(money_supply_m1["DateTime"], errors='coerce')
money_supply_m1["LastUpdate"] = pd.to_datetime(money_supply_m1["LastUpdate"], errors='coerce')

money_supply_m1

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Money Supply M1,1974-06-30,7.177,Monthly,BANGLADESHMONSUPM1,2025-03-07 09:43:00
1,Bangladesh,Money Supply M1,1974-07-31,6.949,Monthly,BANGLADESHMONSUPM1,2025-03-07 09:43:00
2,Bangladesh,Money Supply M1,1974-08-31,6.951,Monthly,BANGLADESHMONSUPM1,2025-03-07 09:43:00
3,Bangladesh,Money Supply M1,1974-09-30,7.049,Monthly,BANGLADESHMONSUPM1,2025-03-07 09:43:00
4,Bangladesh,Money Supply M1,1974-10-31,7.474,Monthly,BANGLADESHMONSUPM1,2025-03-07 09:43:00
...,...,...,...,...,...,...,...
613,Bangladesh,Money Supply M1,2025-07-31,4853.470,Monthly,BANGLADESHMONSUPM1,2025-09-11 04:29:00
614,Bangladesh,Money Supply M1,2025-08-31,4778.330,Monthly,BANGLADESHMONSUPM1,2025-10-20 07:18:00
615,Bangladesh,Money Supply M1,2025-09-30,4708.970,Monthly,BANGLADESHMONSUPM1,2025-11-13 05:24:00
616,Bangladesh,Money Supply M1,2025-10-31,4661.170,Monthly,BANGLADESHMONSUPM1,2025-12-11 02:04:00
617,Bangladesh,Money Supply M1,2025-11-30,4717.410,Monthly,BANGLADESHMONSUPM1,2026-01-12 02:59:00

In [46]:
money_supply_m2 = pd.read_csv("../data/tradingeconomics/Money/Money_Supply_M2.csv")

money_supply_m2["DateTime"] = pd.to_datetime(money_supply_m2["DateTime"], errors='coerce')
money_supply_m2["LastUpdate"] = pd.to_datetime(money_supply_m2["LastUpdate"], errors='coerce')

money_supply_m2

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Money Supply M2,1990-01-31,208.34,Monthly,BANGLADESHMONSUPM2,2012-09-28 19:03:00
1,Bangladesh,Money Supply M2,1990-02-28,209.14,Monthly,BANGLADESHMONSUPM2,2012-09-28 19:03:00
2,Bangladesh,Money Supply M2,1990-03-31,207.37,Monthly,BANGLADESHMONSUPM2,2012-09-28 19:03:00
3,Bangladesh,Money Supply M2,1990-04-30,209.33,Monthly,BANGLADESHMONSUPM2,2014-11-16 21:33:00
4,Bangladesh,Money Supply M2,1990-05-31,208.03,Monthly,BANGLADESHMONSUPM2,2012-09-28 19:03:00
...,...,...,...,...,...,...,...
425,Bangladesh,Money Supply M2,2025-07-31,21679.00,Monthly,BANGLADESHMONSUPM2,2025-09-11 04:57:00
426,Bangladesh,Money Supply M2,2025-08-31,21817.70,Monthly,BANGLADESHMONSUPM2,2025-10-20 07:19:00
427,Bangladesh,Money Supply M2,2025-09-30,21899.90,Monthly,BANGLADESHMONSUPM2,2025-11-13 05:24:00
428,Bangladesh,Money Supply M2,2025-10-31,21950.90,Monthly,BANGLADESHMONSUPM2,2025-12-11 02:08:00
429,Bangladesh,Money Supply M2,2025-11-30,22228.10,Monthly,BANGLADESHMONSUPM2,2026-01-12 03:02:00

In [47]:
money_supply_m3 = pd.read_csv("../data/tradingeconomics/Money/Money_Supply_M3.csv")

money_supply_m3["DateTime"] = pd.to_datetime(money_supply_m3["DateTime"], errors='coerce')
money_supply_m3["LastUpdate"] = pd.to_datetime(money_supply_m3["LastUpdate"], errors='coerce')

money_supply_m3

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Money Supply M3,1999-01-29,73.632,Monthly,BANGLADESHMONSUPM3,2025-03-07 09:49:00
1,Bangladesh,Money Supply M3,1999-02-28,73.298,Monthly,BANGLADESHMONSUPM3,2025-03-07 09:49:00
2,Bangladesh,Money Supply M3,1999-03-31,74.111,Monthly,BANGLADESHMONSUPM3,2025-03-07 09:49:00
3,Bangladesh,Money Supply M3,1999-04-30,74.566,Monthly,BANGLADESHMONSUPM3,2025-03-07 09:49:00
4,Bangladesh,Money Supply M3,1999-05-31,74.295,Monthly,BANGLADESHMONSUPM3,2025-03-07 09:49:00
...,...,...,...,...,...,...,...
318,Bangladesh,Money Supply M3,2025-06-30,2552.901,Monthly,BANGLADESHMONSUPM3,2025-08-26 05:01:00
319,Bangladesh,Money Supply M3,2025-07-31,2546.855,Monthly,BANGLADESHMONSUPM3,2025-09-25 03:09:00
320,Bangladesh,Money Supply M3,2025-08-31,2560.875,Monthly,BANGLADESHMONSUPM3,2025-10-29 04:58:00
321,Bangladesh,Money Supply M3,2025-09-30,2568.886,Monthly,BANGLADESHMONSUPM3,2025-12-05 04:12:00
322,Bangladesh,Money Supply M3,2025-10-31,2575.440,Monthly,BANGLADESHMONSUPM3,2026-01-05 06:13:00

In [48]:
foreign_exchange_reserves = pd.read_csv("../data/tradingeconomics/Money/Foreign_Exchange_Reserves.csv")

foreign_exchange_reserves["DateTime"] = pd.to_datetime(foreign_exchange_reserves["DateTime"], errors='coerce')
foreign_exchange_reserves["LastUpdate"] = pd.to_datetime(foreign_exchange_reserves["LastUpdate"], errors='coerce')

foreign_exchange_reserves

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Foreign Exchange Reserves,2008-06-30,7470.9,Monthly,BANGLADESHFOREXCRES,2016-07-20 16:02:00
1,Bangladesh,Foreign Exchange Reserves,2008-07-31,7741.5,Monthly,BANGLADESHFOREXCRES,2016-07-20 16:02:00
2,Bangladesh,Foreign Exchange Reserves,2008-08-31,9155.7,Monthly,BANGLADESHFOREXCRES,2016-07-20 16:02:00
3,Bangladesh,Foreign Exchange Reserves,2008-09-30,9362.6,Monthly,BANGLADESHFOREXCRES,2016-07-20 16:02:00
4,Bangladesh,Foreign Exchange Reserves,2008-10-31,9544.7,Monthly,BANGLADESHFOREXCRES,2016-07-20 16:02:00
...,...,...,...,...,...,...,...
206,Bangladesh,Foreign Exchange Reserves,2025-08-31,31166.2,Monthly,BANGLADESHFOREXCRES,2025-09-11 07:08:00
207,Bangladesh,Foreign Exchange Reserves,2025-09-30,31426.8,Monthly,BANGLADESHFOREXCRES,2025-10-14 06:27:00
208,Bangladesh,Foreign Exchange Reserves,2025-10-31,32335.2,Monthly,BANGLADESHFOREXCRES,2025-11-13 04:53:00
209,Bangladesh,Foreign Exchange Reserves,2025-11-30,31093.4,Monthly,BANGLADESHFOREXCRES,2026-01-12 03:26:00
210,Bangladesh,Foreign Exchange Reserves,2025-12-31,33187.9,Monthly,BANGLADESHFOREXCRES,2026-01-12 03:26:00

In [49]:
loans_to_private_sector = pd.read_csv("../data/tradingeconomics/Money/Loans_to_Private_Sector.csv")

loans_to_private_sector["DateTime"] = pd.to_datetime(loans_to_private_sector["DateTime"], errors='coerce')
loans_to_private_sector["LastUpdate"] = pd.to_datetime(loans_to_private_sector["LastUpdate"], errors='coerce')

loans_to_private_sector

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Loans to Private Sector,1990-07-31,152.33,Monthly,BANGLADESHLOATOPRISE,2014-11-16 21:32:00
1,Bangladesh,Loans to Private Sector,1990-08-31,154.84,Monthly,BANGLADESHLOATOPRISE,2014-11-16 21:32:00
2,Bangladesh,Loans to Private Sector,1990-09-30,158.04,Monthly,BANGLADESHLOATOPRISE,2014-11-16 21:32:00
3,Bangladesh,Loans to Private Sector,1990-10-31,156.06,Monthly,BANGLADESHLOATOPRISE,2014-11-16 21:32:00
4,Bangladesh,Loans to Private Sector,1990-11-30,157.02,Monthly,BANGLADESHLOATOPRISE,2014-11-16 21:32:00
...,...,...,...,...,...,...,...
480,Bangladesh,Loans to Private Sector,2025-06-30,16815.93,Monthly,BANGLADESHLOATOPRISE,2025-08-26 04:38:00
481,Bangladesh,Loans to Private Sector,2025-07-31,16777.13,Monthly,BANGLADESHLOATOPRISE,2025-09-25 03:07:00
482,Bangladesh,Loans to Private Sector,2025-08-31,16807.89,Monthly,BANGLADESHLOATOPRISE,2025-10-29 05:06:00
483,Bangladesh,Loans to Private Sector,2025-09-30,16894.61,Monthly,BANGLADESHLOATOPRISE,2025-12-05 04:06:00
484,Bangladesh,Loans to Private Sector,2025-10-31,16921.93,Monthly,BANGLADESHLOATOPRISE,2026-01-05 06:10:00

In [50]:
deposit_interest_rate = pd.read_csv("../data/tradingeconomics/Money/Deposit_Interest_Rate.csv")

deposit_interest_rate["DateTime"] = pd.to_datetime(deposit_interest_rate["DateTime"], errors='coerce')
deposit_interest_rate["LastUpdate"] = pd.to_datetime(deposit_interest_rate["LastUpdate"], errors='coerce')

deposit_interest_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Deposit Interest Rate,1980-12-31,8.25,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
1,Bangladesh,Deposit Interest Rate,1981-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
2,Bangladesh,Deposit Interest Rate,1982-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
3,Bangladesh,Deposit Interest Rate,1983-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
4,Bangladesh,Deposit Interest Rate,1984-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
5,Bangladesh,Deposit Interest Rate,1985-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
6,Bangladesh,Deposit Interest Rate,1986-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
7,Bangladesh,Deposit Interest Rate,1987-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
8,Bangladesh,Deposit Interest Rate,1988-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
9,Bangladesh,Deposit Interest Rate,1989-12-31,12.00,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
10,Bangladesh,Deposit Interest Rate,1990-12-31,12.04,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
11,Bangladesh,Deposit Interest Rate,1991-12-31,12.05,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
12,Bangladesh,Deposit Interest Rate,1992-12-31,10.47,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
13,Bangladesh,Deposit Interest Rate,1993-12-31,8.18,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
14,Bangladesh,Deposit Interest Rate,1994-12-31,6.40,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
15,Bangladesh,Deposit Interest Rate,1995-12-31,6.04,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
16,Bangladesh,Deposit Interest Rate,1996-12-31,7.28,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
17,Bangladesh,Deposit Interest Rate,1997-12-31,8.11,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
18,Bangladesh,Deposit Interest Rate,1998-12-31,8.42,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
19,Bangladesh,Deposit Interest Rate,1999-12-31,8.74,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
20,Bangladesh,Deposit Interest Rate,2000-12-31,8.56,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
21,Bangladesh,Deposit Interest Rate,2001-12-31,8.50,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
22,Bangladesh,Deposit Interest Rate,2002-12-31,8.17,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
23,Bangladesh,Deposit Interest Rate,2003-12-31,7.82,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
24,Bangladesh,Deposit Interest Rate,2004-12-31,7.11,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
25,Bangladesh,Deposit Interest Rate,2005-12-31,8.09,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
26,Bangladesh,Deposit Interest Rate,2006-12-31,9.11,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
27,Bangladesh,Deposit Interest Rate,2007-12-31,9.18,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
28,Bangladesh,Deposit Interest Rate,2008-12-31,9.65,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
29,Bangladesh,Deposit Interest Rate,2009-12-31,8.21,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
30,Bangladesh,Deposit Interest Rate,2010-12-31,7.14,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
31,Bangladesh,Deposit Interest Rate,2011-12-31,10.02,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
32,Bangladesh,Deposit Interest Rate,2012-12-31,11.69,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
33,Bangladesh,Deposit Interest Rate,2013-12-31,11.19,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
34,Bangladesh,Deposit Interest Rate,2014-12-31,9.08,Yearly,BGDFRINRDPST,2015-12-03 14:33:00
35,Bangladesh,Deposit Interest Rate,2015-12-31,8.20,Yearly,BGDFRINRDPST,2016-07-20 15:57:00
36,Bangladesh,Deposit Interest Rate,2016-12-31,6.20,Yearly,BGDFRINRDPST,2017-04-21 10:36:00
37,Bangladesh,Deposit Interest Rate,2017-12-31,5.61,Yearly,BGDFRINRDPST,2018-05-09 16:49:00
38,Bangladesh,Deposit Interest Rate,2018-12-31,6.66,Yearly,BGDFRINRDPST,2019-07-26 11:22:00
39,Bangladesh,Deposit Interest Rate,2019-12-31,6.78,Yearly,BGDFRINRDPST,2020-06-24 21:25:00
40,Bangladesh,Deposit Interest Rate,2020-12-31,6.07,Yearly,BGDFRINRDPST,2021-07-14 18:50:00
41,Bangladesh,Deposit Interest Rate,2021-12-31,5.05,Yearly,BGDFRINRDPST,2022-05-02 15:38:00
42,Bangladesh,Deposit Interest Rate,2022-12-31,5.56,Yearly,BGDFRINRDPST,2024-01-12 06:54:00
43,Bangladesh,Deposit Interest Rate,2023-12-31,6.52,Yearly,BGDFRINRDPST,2024-06-06 01:05:00
44,Bangladesh,Deposit Interest Rate,2024-12-31,8.53,Yearly,BGDFRINRDPST,2025-02-25 10:33:00

<br> <br> 

## Trade

In [51]:
balance_of_trade = pd.read_csv("../data/tradingeconomics/Trade/Balance_of_Trade.csv")

balance_of_trade["DateTime"] = pd.to_datetime(balance_of_trade["DateTime"], errors='coerce')
balance_of_trade["LastUpdate"] = pd.to_datetime(balance_of_trade["LastUpdate"], errors='coerce')

balance_of_trade

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Balance of Trade,1976-03-31,-1.20,Monthly,BangladeshBT,2014-08-26 18:11:00
1,Bangladesh,Balance of Trade,1976-04-30,-0.60,Monthly,BangladeshBT,2014-08-26 18:11:00
2,Bangladesh,Balance of Trade,1976-05-31,-0.60,Monthly,BangladeshBT,2014-11-16 21:27:00
3,Bangladesh,Balance of Trade,1976-06-30,-1.40,Monthly,BangladeshBT,2014-08-26 18:11:00
4,Bangladesh,Balance of Trade,1976-07-31,-0.70,Monthly,BangladeshBT,2014-08-26 18:11:00
...,...,...,...,...,...,...,...
589,Bangladesh,Balance of Trade,2025-06-30,-181.83,Monthly,BangladeshBT,2025-08-26 05:05:00
590,Bangladesh,Balance of Trade,2025-07-31,-211.58,Monthly,BangladeshBT,2025-09-25 02:42:00
591,Bangladesh,Balance of Trade,2025-08-31,-118.86,Monthly,BangladeshBT,2025-10-29 06:01:00
592,Bangladesh,Balance of Trade,2025-09-30,-203.34,Monthly,BangladeshBT,2026-01-05 06:21:00
593,Bangladesh,Balance of Trade,2025-10-31,-219.48,Monthly,BangladeshBT,2026-01-05 06:21:00

In [52]:
current_account = pd.read_csv("../data/tradingeconomics/Trade/Current_Account.csv")

current_account["DateTime"] = pd.to_datetime(current_account["DateTime"], errors='coerce')
current_account["LastUpdate"] = pd.to_datetime(current_account["LastUpdate"], errors='coerce')

current_account

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Current Account,2005-06-30,-557.00,Monthly,BangladeshCA,2011-06-27 00:00:00
1,Bangladesh,Current Account,2006-06-30,824.00,Monthly,BangladeshCA,2011-06-27 00:00:00
2,Bangladesh,Current Account,2007-06-30,952.00,Monthly,BangladeshCA,2011-06-27 00:00:00
3,Bangladesh,Current Account,2008-06-30,680.00,Monthly,BangladeshCA,2011-06-27 00:00:00
4,Bangladesh,Current Account,2008-09-30,366.00,Monthly,BangladeshCA,2011-06-27 00:00:00
...,...,...,...,...,...,...,...
174,Bangladesh,Current Account,2025-05-31,1126.51,Monthly,BangladeshCA,2025-09-25 03:33:00
175,Bangladesh,Current Account,2025-06-30,734.36,Monthly,BangladeshCA,2025-09-25 03:33:00
176,Bangladesh,Current Account,2025-07-31,300.46,Monthly,BangladeshCA,2025-11-14 03:30:00
177,Bangladesh,Current Account,2025-08-31,294.02,Monthly,BangladeshCA,2025-12-05 03:58:00
178,Bangladesh,Current Account,2025-09-30,-1129.87,Monthly,BangladeshCA,2026-01-05 05:55:00

In [53]:
current_account_to_gdp = pd.read_csv("../data/tradingeconomics/Trade/Current_Account_to_GDP.csv")

current_account_to_gdp["DateTime"] = pd.to_datetime(current_account_to_gdp["DateTime"], errors='coerce')
current_account_to_gdp["LastUpdate"] = pd.to_datetime(current_account_to_gdp["LastUpdate"], errors='coerce')

current_account_to_gdp

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Current Account to GDP,1980-12-31,-0.8,Yearly,BGDCA2GDP,2025-01-28 07:24:00
1,Bangladesh,Current Account to GDP,1981-12-31,-1.8,Yearly,BGDCA2GDP,2025-01-28 07:24:00
2,Bangladesh,Current Account to GDP,1982-12-31,-2.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
3,Bangladesh,Current Account to GDP,1983-12-31,-2.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
4,Bangladesh,Current Account to GDP,1984-12-31,-1.9,Yearly,BGDCA2GDP,2025-01-28 07:24:00
5,Bangladesh,Current Account to GDP,1985-12-31,-2.4,Yearly,BGDCA2GDP,2025-01-28 07:24:00
6,Bangladesh,Current Account to GDP,1986-12-31,-2.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
7,Bangladesh,Current Account to GDP,1987-12-31,-1.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
8,Bangladesh,Current Account to GDP,1988-12-31,-2.4,Yearly,BGDCA2GDP,2025-01-28 07:24:00
9,Bangladesh,Current Account to GDP,1989-12-31,-3.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
10,Bangladesh,Current Account to GDP,1990-12-31,-2.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
11,Bangladesh,Current Account to GDP,1991-12-31,-1.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
12,Bangladesh,Current Account to GDP,1992-12-31,-0.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
13,Bangladesh,Current Account to GDP,1993-12-31,-0.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
14,Bangladesh,Current Account to GDP,1994-12-31,-0.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
15,Bangladesh,Current Account to GDP,1995-12-31,-1.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
16,Bangladesh,Current Account to GDP,1996-12-31,-1.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
17,Bangladesh,Current Account to GDP,1997-12-31,-1.4,Yearly,BGDCA2GDP,2025-01-28 07:24:00
18,Bangladesh,Current Account to GDP,1998-12-31,-0.9,Yearly,BGDCA2GDP,2025-01-28 07:24:00
19,Bangladesh,Current Account to GDP,1999-12-31,-0.6,Yearly,BGDCA2GDP,2025-01-28 07:24:00
20,Bangladesh,Current Account to GDP,2000-12-31,-0.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
21,Bangladesh,Current Account to GDP,2001-12-31,-1.6,Yearly,BGDCA2GDP,2025-01-28 07:24:00
22,Bangladesh,Current Account to GDP,2002-12-31,0.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
23,Bangladesh,Current Account to GDP,2003-12-31,0.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
24,Bangladesh,Current Account to GDP,2004-12-31,0.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
25,Bangladesh,Current Account to GDP,2005-12-31,-0.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
26,Bangladesh,Current Account to GDP,2006-12-31,0.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
27,Bangladesh,Current Account to GDP,2007-12-31,1.0,Yearly,BGDCA2GDP,2025-01-28 07:24:00
28,Bangladesh,Current Account to GDP,2008-12-31,0.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
29,Bangladesh,Current Account to GDP,2009-12-31,1.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
30,Bangladesh,Current Account to GDP,2010-12-31,2.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
31,Bangladesh,Current Account to GDP,2011-12-31,-1.4,Yearly,BGDCA2GDP,2025-01-28 07:24:00
32,Bangladesh,Current Account to GDP,2012-12-31,-0.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
33,Bangladesh,Current Account to GDP,2013-12-31,1.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
34,Bangladesh,Current Account to GDP,2014-12-31,0.7,Yearly,BGDCA2GDP,2025-01-28 07:24:00
35,Bangladesh,Current Account to GDP,2015-12-31,1.2,Yearly,BGDCA2GDP,2025-01-28 07:24:00
36,Bangladesh,Current Account to GDP,2016-12-31,1.6,Yearly,BGDCA2GDP,2025-01-28 07:24:00
37,Bangladesh,Current Account to GDP,2017-12-31,-0.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
38,Bangladesh,Current Account to GDP,2018-12-31,-3.0,Yearly,BGDCA2GDP,2025-01-28 07:24:00
39,Bangladesh,Current Account to GDP,2019-12-31,-1.3,Yearly,BGDCA2GDP,2025-01-28 07:24:00
40,Bangladesh,Current Account to GDP,2020-12-31,-1.5,Yearly,BGDCA2GDP,2025-01-28 07:24:00
41,Bangladesh,Current Account to GDP,2021-12-31,-1.1,Yearly,BGDCA2GDP,2025-01-28 07:24:00
42,Bangladesh,Current Account to GDP,2022-12-31,-4.0,Yearly,BGDCA2GDP,2025-01-28 07:24:00
43,Bangladesh,Current Account to GDP,2023-12-31,-2.6,Yearly,BGDCA2GDP,2025-01-28 07:24:00
44,Bangladesh,Current Account to GDP,2024-12-31,-1.5,Yearly,BGDCA2GDP,2026-01-05 16:12:00

In [54]:
exports = pd.read_csv("../data/tradingeconomics/Trade/Exports.csv")

exports["DateTime"] = pd.to_datetime(exports["DateTime"], errors='coerce')
exports["LastUpdate"] = pd.to_datetime(exports["LastUpdate"], errors='coerce')

exports

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Exports,1972-01-31,0.09,Monthly,BangladeshEx,2014-11-16 21:29:00
1,Bangladesh,Exports,1972-02-29,0.05,Monthly,BangladeshEx,2014-08-26 18:09:00
2,Bangladesh,Exports,1972-03-31,0.13,Monthly,BangladeshEx,2014-08-26 18:09:00
3,Bangladesh,Exports,1972-04-30,0.13,Monthly,BangladeshEx,2014-11-16 21:29:00
4,Bangladesh,Exports,1972-05-31,0.22,Monthly,BangladeshEx,2014-08-26 18:09:00
...,...,...,...,...,...,...,...
639,Bangladesh,Exports,2025-06-30,407.54,Monthly,BangladeshEx,2025-08-26 04:48:00
640,Bangladesh,Exports,2025-07-31,484.73,Monthly,BangladeshEx,2025-09-25 02:43:00
641,Bangladesh,Exports,2025-08-31,462.35,Monthly,BangladeshEx,2025-10-29 05:32:00
642,Bangladesh,Exports,2025-09-30,447.21,Monthly,BangladeshEx,2025-12-15 04:35:00
643,Bangladesh,Exports,2025-10-31,420.37,Monthly,BangladeshEx,2026-01-05 06:15:00

In [55]:
imports = pd.read_csv("../data/tradingeconomics/Trade/Imports.csv")

imports["DateTime"] = pd.to_datetime(imports["DateTime"], errors='coerce')
imports["LastUpdate"] = pd.to_datetime(imports["LastUpdate"], errors='coerce')

imports

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Imports,1976-03-31,1.74,Monthly,BangladeshIm,2014-08-26 18:10:00
1,Bangladesh,Imports,1976-04-30,1.02,Monthly,BangladeshIm,2014-08-26 18:10:00
2,Bangladesh,Imports,1976-05-31,1.20,Monthly,BangladeshIm,2014-11-16 21:31:00
3,Bangladesh,Imports,1976-06-30,1.98,Monthly,BangladeshIm,2014-08-26 18:10:00
4,Bangladesh,Imports,1976-07-31,1.27,Monthly,BangladeshIm,2014-08-26 18:10:00
...,...,...,...,...,...,...,...
589,Bangladesh,Imports,2025-06-30,589.38,Monthly,BangladeshIm,2025-08-26 04:50:00
590,Bangladesh,Imports,2025-07-31,696.31,Monthly,BangladeshIm,2025-09-25 02:43:00
591,Bangladesh,Imports,2025-08-31,581.21,Monthly,BangladeshIm,2025-10-29 05:36:00
592,Bangladesh,Imports,2025-09-30,650.55,Monthly,BangladeshIm,2026-01-05 06:19:00
593,Bangladesh,Imports,2025-10-31,639.85,Monthly,BangladeshIm,2026-01-05 06:19:00

In [56]:
capital_flows = pd.read_csv("../data/tradingeconomics/Trade/Capital_Flows.csv")

capital_flows["DateTime"] = pd.to_datetime(capital_flows["DateTime"], errors='coerce')
capital_flows["LastUpdate"] = pd.to_datetime(capital_flows["LastUpdate"], errors='coerce')

capital_flows

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Capital Flows,1997-07-31,-4.420,Monthly,BANGLADESHCAPFLO,2014-05-02 16:52:00
1,Bangladesh,Capital Flows,1997-08-31,2.110,Monthly,BANGLADESHCAPFLO,2014-05-02 16:52:00
2,Bangladesh,Capital Flows,1997-09-30,-5.910,Monthly,BANGLADESHCAPFLO,2014-05-02 16:52:00
3,Bangladesh,Capital Flows,1997-10-31,0.620,Monthly,BANGLADESHCAPFLO,2014-05-02 16:52:00
4,Bangladesh,Capital Flows,1997-11-30,-1.150,Monthly,BANGLADESHCAPFLO,2014-11-16 21:28:00
...,...,...,...,...,...,...,...
328,Bangladesh,Capital Flows,2025-05-31,2.850,Monthly,BANGLADESHCAPFLO,2025-08-26 05:02:00
329,Bangladesh,Capital Flows,2025-06-30,6.860,Monthly,BANGLADESHCAPFLO,2025-09-25 03:26:00
330,Bangladesh,Capital Flows,2025-07-31,0.040,Monthly,BANGLADESHCAPFLO,2025-11-14 03:34:00
331,Bangladesh,Capital Flows,2025-08-31,1.004,Monthly,BANGLADESHCAPFLO,2025-12-05 04:02:00
332,Bangladesh,Capital Flows,2025-09-30,10.340,Monthly,BANGLADESHCAPFLO,2026-01-05 05:58:00

In [57]:
remittances = pd.read_csv("../data/tradingeconomics/Trade/Remittances.csv")

remittances["DateTime"] = pd.to_datetime(remittances["DateTime"], errors='coerce')
remittances["LastUpdate"] = pd.to_datetime(remittances["LastUpdate"], errors='coerce')

remittances

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Remittances,2012-02-29,1133.00,Monthly,BANGLADESHREM,2013-10-09 10:13:00
1,Bangladesh,Remittances,2012-03-31,1109.10,Monthly,BANGLADESHREM,2013-10-09 10:13:00
2,Bangladesh,Remittances,2012-04-30,1083.90,Monthly,BANGLADESHREM,2013-10-09 10:13:00
3,Bangladesh,Remittances,2012-05-31,1156.80,Monthly,BANGLADESHREM,2013-10-09 10:13:00
4,Bangladesh,Remittances,2012-06-30,1070.90,Monthly,BANGLADESHREM,2013-10-09 10:13:00
...,...,...,...,...,...,...,...
160,Bangladesh,Remittances,2025-06-30,2822.53,Monthly,BANGLADESHREM,2025-08-11 03:59:00
161,Bangladesh,Remittances,2025-07-31,2477.87,Monthly,BANGLADESHREM,2025-09-10 08:40:00
162,Bangladesh,Remittances,2025-08-31,2421.89,Monthly,BANGLADESHREM,2025-10-17 04:29:00
163,Bangladesh,Remittances,2025-09-30,2685.56,Monthly,BANGLADESHREM,2025-11-13 04:56:00
164,Bangladesh,Remittances,2025-10-31,2562.44,Monthly,BANGLADESHREM,2025-12-16 01:38:00

In [58]:
gold_reserves = pd.read_csv("../data/tradingeconomics/Trade/Gold_Reserves.csv")

gold_reserves["DateTime"] = pd.to_datetime(gold_reserves["DateTime"], errors='coerce')
gold_reserves["LastUpdate"] = pd.to_datetime(gold_reserves["LastUpdate"], errors='coerce')

gold_reserves

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Gold Reserves,2000-03-31,3.29,Quarterly,BANGLADESHGOLRES,2014-04-16 18:42:00
1,Bangladesh,Gold Reserves,2000-06-30,3.34,Quarterly,BANGLADESHGOLRES,2014-04-16 18:42:00
2,Bangladesh,Gold Reserves,2000-09-30,3.34,Quarterly,BANGLADESHGOLRES,2014-04-16 18:42:00
3,Bangladesh,Gold Reserves,2000-12-31,3.38,Quarterly,BANGLADESHGOLRES,2014-04-16 18:42:00
4,Bangladesh,Gold Reserves,2001-03-31,3.38,Quarterly,BANGLADESHGOLRES,2014-04-16 18:42:00
...,...,...,...,...,...,...,...
99,Bangladesh,Gold Reserves,2024-09-30,14.26,Quarterly,BANGLADESHGOLRES,2025-02-10 01:22:00
100,Bangladesh,Gold Reserves,2024-12-31,14.28,Quarterly,BANGLADESHGOLRES,2025-05-05 06:21:00
101,Bangladesh,Gold Reserves,2025-03-31,14.28,Quarterly,BANGLADESHGOLRES,2025-05-05 06:22:00
102,Bangladesh,Gold Reserves,2025-06-30,14.28,Quarterly,BANGLADESHGOLRES,2025-08-06 03:29:00
103,Bangladesh,Gold Reserves,2025-09-30,14.28,Quarterly,BANGLADESHGOLRES,2025-11-05 03:49:00

In [59]:
external_debt = pd.read_csv("../data/tradingeconomics/Trade/External_Debt.csv")

external_debt["DateTime"] = pd.to_datetime(external_debt["DateTime"], errors='coerce')
external_debt["LastUpdate"] = pd.to_datetime(external_debt["LastUpdate"], errors='coerce')

external_debt

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,External Debt,2001-12-31,16.24,Yearly,BANGLADESHEXTDEB,2014-08-26 13:10:00
1,Bangladesh,External Debt,2002-12-31,16.17,Yearly,BANGLADESHEXTDEB,2014-08-26 13:09:00
2,Bangladesh,External Debt,2003-12-31,17.00,Yearly,BANGLADESHEXTDEB,2014-08-26 13:08:00
3,Bangladesh,External Debt,2004-12-31,18.00,Yearly,BANGLADESHEXTDEB,2014-08-26 13:08:00
4,Bangladesh,External Debt,2005-12-31,18.41,Yearly,BANGLADESHEXTDEB,2014-08-26 13:07:00
5,Bangladesh,External Debt,2006-12-31,18.60,Yearly,BANGLADESHEXTDEB,2014-08-26 13:06:00
6,Bangladesh,External Debt,2007-12-31,19.35,Yearly,BANGLADESHEXTDEB,2014-08-26 13:06:00
7,Bangladesh,External Debt,2008-12-31,20.26,Yearly,BANGLADESHEXTDEB,2014-08-26 13:05:00
8,Bangladesh,External Debt,2009-12-31,20.86,Yearly,BANGLADESHEXTDEB,2014-08-26 13:04:00
9,Bangladesh,External Debt,2010-12-31,20.34,Yearly,BANGLADESHEXTDEB,2014-08-26 13:04:00
10,Bangladesh,External Debt,2011-12-31,22.10,Yearly,BANGLADESHEXTDEB,2014-08-26 13:03:00
11,Bangladesh,External Debt,2012-12-31,22.10,Yearly,BANGLADESHEXTDEB,2014-08-26 13:02:00
12,Bangladesh,External Debt,2013-12-31,22.40,Yearly,BANGLADESHEXTDEB,2014-08-26 13:02:00
13,Bangladesh,External Debt,2014-12-31,24.40,Yearly,BANGLADESHEXTDEB,2016-05-02 17:43:00
14,Bangladesh,External Debt,2015-12-31,23.90,Yearly,BANGLADESHEXTDEB,2017-01-02 16:58:00
15,Bangladesh,External Debt,2016-12-31,26.31,Yearly,BANGLADESHEXTDEB,2018-07-20 13:44:00
16,Bangladesh,External Debt,2017-12-31,28.34,Yearly,BANGLADESHEXTDEB,2019-05-06 14:29:00
17,Bangladesh,External Debt,2018-12-31,33.51,Yearly,BANGLADESHEXTDEB,2020-04-29 21:38:00
18,Bangladesh,External Debt,2019-12-31,38.48,Yearly,BANGLADESHEXTDEB,2021-03-02 15:22:00
19,Bangladesh,External Debt,2020-12-31,44.20,Yearly,BANGLADESHEXTDEB,2021-03-02 15:23:00
20,Bangladesh,External Debt,2021-12-31,50.88,Yearly,BANGLADESHEXTDEB,2023-07-14 09:41:00
21,Bangladesh,External Debt,2022-12-31,55.60,Yearly,BANGLADESHEXTDEB,2024-05-14 09:24:00
22,Bangladesh,External Debt,2023-12-31,62.41,Yearly,BANGLADESHEXTDEB,2025-05-26 06:44:00
23,Bangladesh,External Debt,2024-12-31,69.65,Yearly,BANGLADESHEXTDEB,2025-05-26 06:45:00

In [60]:
foreign_direct_investment = pd.read_csv("../data/tradingeconomics/Trade/Foreign_Direct_Investment.csv")

foreign_direct_investment["DateTime"] = pd.to_datetime(foreign_direct_investment["DateTime"], errors='coerce')
foreign_direct_investment["LastUpdate"] = pd.to_datetime(foreign_direct_investment["LastUpdate"], errors='coerce')

foreign_direct_investment

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Foreign Direct Investment,2002-12-31,391,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
1,Bangladesh,Foreign Direct Investment,2003-12-31,376,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
2,Bangladesh,Foreign Direct Investment,2004-12-31,276,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
3,Bangladesh,Foreign Direct Investment,2005-12-31,800,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
4,Bangladesh,Foreign Direct Investment,2006-12-31,743,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
5,Bangladesh,Foreign Direct Investment,2007-12-31,793,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
6,Bangladesh,Foreign Direct Investment,2008-12-31,748,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
7,Bangladesh,Foreign Direct Investment,2009-12-31,961,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
8,Bangladesh,Foreign Direct Investment,2010-12-31,913,Yearly,BANGLADESHFORDIRINV,2014-08-26 13:48:00
9,Bangladesh,Foreign Direct Investment,2011-12-31,775,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:39:00
10,Bangladesh,Foreign Direct Investment,2012-12-31,1191,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:39:00
11,Bangladesh,Foreign Direct Investment,2013-12-31,1726,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:39:00
12,Bangladesh,Foreign Direct Investment,2014-12-31,1474,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:39:00
13,Bangladesh,Foreign Direct Investment,2015-12-31,1172,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:50:00
14,Bangladesh,Foreign Direct Investment,2016-12-31,1285,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:50:00
15,Bangladesh,Foreign Direct Investment,2017-12-31,1706,Yearly,BANGLADESHFORDIRINV,2018-07-20 13:50:00
16,Bangladesh,Foreign Direct Investment,2018-12-31,1583,Yearly,BANGLADESHFORDIRINV,2019-05-06 14:14:00
17,Bangladesh,Foreign Direct Investment,2019-12-31,2650,Yearly,BANGLADESHFORDIRINV,2020-04-29 21:46:00
18,Bangladesh,Foreign Direct Investment,2020-12-31,1510,Yearly,BANGLADESHFORDIRINV,2021-03-02 15:33:00
19,Bangladesh,Foreign Direct Investment,2021-12-31,1355,Yearly,BANGLADESHFORDIRINV,2022-10-19 07:04:00
20,Bangladesh,Foreign Direct Investment,2022-12-31,1827,Yearly,BANGLADESHFORDIRINV,2024-05-14 09:36:00
21,Bangladesh,Foreign Direct Investment,2023-12-31,1649,Yearly,BANGLADESHFORDIRINV,2024-05-14 09:36:00
22,Bangladesh,Foreign Direct Investment,2024-12-31,1697,Yearly,BANGLADESHFORDIRINV,2025-05-26 06:42:00

In [61]:
terrorism_index = pd.read_csv("../data/tradingeconomics/Trade/Terrorism_Index.csv")

terrorism_index["DateTime"] = pd.to_datetime(terrorism_index["DateTime"], errors='coerce')
terrorism_index["LastUpdate"] = pd.to_datetime(terrorism_index["LastUpdate"], errors='coerce')

terrorism_index

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Terrorism Index,2002-12-31,5.340,Yearly,BangladeshTerInd,2015-11-24 19:02:00
1,Bangladesh,Terrorism Index,2003-12-31,4.760,Yearly,BangladeshTerInd,2015-11-24 19:02:00
2,Bangladesh,Terrorism Index,2004-12-31,5.030,Yearly,BangladeshTerInd,2015-11-24 19:02:00
3,Bangladesh,Terrorism Index,2005-12-31,5.510,Yearly,BangladeshTerInd,2015-11-24 19:02:00
4,Bangladesh,Terrorism Index,2006-12-31,5.250,Yearly,BangladeshTerInd,2015-11-24 19:02:00
5,Bangladesh,Terrorism Index,2007-12-31,4.670,Yearly,BangladeshTerInd,2015-11-24 19:02:00
6,Bangladesh,Terrorism Index,2008-12-31,4.510,Yearly,BangladeshTerInd,2015-11-24 19:02:00
7,Bangladesh,Terrorism Index,2009-12-31,4.510,Yearly,BangladeshTerInd,2015-11-24 19:02:00
8,Bangladesh,Terrorism Index,2010-12-31,4.620,Yearly,BangladeshTerInd,2015-11-24 19:02:00
9,Bangladesh,Terrorism Index,2011-12-31,4.229,Yearly,BangladeshTerInd,2022-09-19 12:40:00
10,Bangladesh,Terrorism Index,2012-12-31,4.460,Yearly,BangladeshTerInd,2022-09-19 12:53:00
11,Bangladesh,Terrorism Index,2013-12-31,4.527,Yearly,BangladeshTerInd,2022-09-19 13:51:00
12,Bangladesh,Terrorism Index,2014-12-31,4.191,Yearly,BangladeshTerInd,2022-09-19 13:55:00
13,Bangladesh,Terrorism Index,2015-12-31,5.392,Yearly,BangladeshTerInd,2022-09-19 13:58:00
14,Bangladesh,Terrorism Index,2016-12-31,5.752,Yearly,BangladeshTerInd,2022-09-19 14:00:00
15,Bangladesh,Terrorism Index,2017-12-31,5.593,Yearly,BangladeshTerInd,2022-09-19 14:03:00
16,Bangladesh,Terrorism Index,2018-12-31,5.032,Yearly,BangladeshTerInd,2022-09-19 14:05:00
17,Bangladesh,Terrorism Index,2019-12-31,4.752,Yearly,BangladeshTerInd,2022-09-19 14:07:00
18,Bangladesh,Terrorism Index,2020-12-31,4.421,Yearly,BangladeshTerInd,2022-09-19 14:09:00
19,Bangladesh,Terrorism Index,2021-12-31,4.411,Yearly,BangladeshTerInd,2022-09-19 14:11:00
20,Bangladesh,Terrorism Index,2022-12-31,3.827,Yearly,BangladeshTerInd,2023-09-15 09:35:00
21,Bangladesh,Terrorism Index,2023-12-31,3.317,Yearly,BangladeshTerInd,2024-03-05 08:50:00
22,Bangladesh,Terrorism Index,2024-12-31,3.030,Yearly,BangladeshTerInd,2025-03-21 08:18:00

<br> <br> 

## Government

In [62]:
government_debt_to_gdp = pd.read_csv("../data/tradingeconomics/Government/Government_Debt_to_GDP.csv")

government_debt_to_gdp["DateTime"] = pd.to_datetime(government_debt_to_gdp["DateTime"], errors='coerce')
government_debt_to_gdp["LastUpdate"] = pd.to_datetime(government_debt_to_gdp["LastUpdate"], errors='coerce')

government_debt_to_gdp

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Debt to GDP,1995-12-31,49.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
1,Bangladesh,Government Debt to GDP,1996-12-31,43.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
2,Bangladesh,Government Debt to GDP,1997-12-31,43.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
3,Bangladesh,Government Debt to GDP,1998-12-31,40.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
4,Bangladesh,Government Debt to GDP,1999-12-31,42.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
5,Bangladesh,Government Debt to GDP,2000-12-31,46.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
6,Bangladesh,Government Debt to GDP,2001-12-31,46.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
7,Bangladesh,Government Debt to GDP,2002-12-31,50.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
8,Bangladesh,Government Debt to GDP,2003-12-31,49.0,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
9,Bangladesh,Government Debt to GDP,2004-12-31,48.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
10,Bangladesh,Government Debt to GDP,2005-12-31,46.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
11,Bangladesh,Government Debt to GDP,2006-12-31,40.2,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
12,Bangladesh,Government Debt to GDP,2007-12-31,38.6,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
13,Bangladesh,Government Debt to GDP,2008-12-31,37.1,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
14,Bangladesh,Government Debt to GDP,2009-12-31,35.9,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
15,Bangladesh,Government Debt to GDP,2010-12-31,32.3,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
16,Bangladesh,Government Debt to GDP,2011-12-31,32.4,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
17,Bangladesh,Government Debt to GDP,2012-12-31,31.8,Yearly,BGDDebt2GDP,2016-09-07 14:23:00
18,Bangladesh,Government Debt to GDP,2013-12-31,30.4,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
19,Bangladesh,Government Debt to GDP,2014-12-31,29.6,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
20,Bangladesh,Government Debt to GDP,2015-12-31,27.7,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
21,Bangladesh,Government Debt to GDP,2016-12-31,27.7,Yearly,BGDDebt2GDP,2018-03-12 14:08:00
22,Bangladesh,Government Debt to GDP,2017-12-31,27.0,Yearly,BGDDebt2GDP,2019-05-02 14:31:00
23,Bangladesh,Government Debt to GDP,2018-12-31,25.7,Yearly,BGDDebt2GDP,2023-07-14 09:49:00
24,Bangladesh,Government Debt to GDP,2019-12-31,27.0,Yearly,BGDDebt2GDP,2023-07-14 09:48:00
25,Bangladesh,Government Debt to GDP,2020-12-31,28.1,Yearly,BGDDebt2GDP,2023-07-14 09:48:00
26,Bangladesh,Government Debt to GDP,2021-12-31,29.3,Yearly,BGDDebt2GDP,2024-11-20 01:35:00
27,Bangladesh,Government Debt to GDP,2022-12-31,29.5,Yearly,BGDDebt2GDP,2024-11-20 01:35:00
28,Bangladesh,Government Debt to GDP,2023-12-31,31.6,Yearly,BGDDebt2GDP,2025-09-02 06:11:00
29,Bangladesh,Government Debt to GDP,2024-12-31,32.2,Yearly,BGDDebt2GDP,2025-09-02 06:11:00

In [63]:
government_budget = pd.read_csv("../data/tradingeconomics/Government/Government_Budget.csv")

government_budget["DateTime"] = pd.to_datetime(government_budget["DateTime"], errors='coerce')
government_budget["LastUpdate"] = pd.to_datetime(government_budget["LastUpdate"], errors='coerce')

government_budget

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Budget,1991-12-31,-3.30,Yearly,BangladeshGB,2016-09-07 13:56:00
1,Bangladesh,Government Budget,1992-12-31,-2.10,Yearly,BangladeshGB,2016-09-07 13:56:00
2,Bangladesh,Government Budget,1993-12-31,-1.30,Yearly,BangladeshGB,2016-09-07 13:56:00
3,Bangladesh,Government Budget,1994-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
4,Bangladesh,Government Budget,1995-12-31,-2.20,Yearly,BangladeshGB,2015-06-12 14:23:00
5,Bangladesh,Government Budget,1996-12-31,-3.00,Yearly,BangladeshGB,2015-06-12 14:23:00
6,Bangladesh,Government Budget,1997-12-31,-2.00,Yearly,BangladeshGB,2015-06-12 14:23:00
7,Bangladesh,Government Budget,1998-12-31,-2.10,Yearly,BangladeshGB,2015-06-12 14:23:00
8,Bangladesh,Government Budget,1999-12-31,-3.20,Yearly,BangladeshGB,2015-06-12 14:23:00
9,Bangladesh,Government Budget,2000-12-31,-4.50,Yearly,BangladeshGB,2015-06-12 14:23:00
10,Bangladesh,Government Budget,2001-12-31,-4.10,Yearly,BangladeshGB,2015-06-12 14:23:00
11,Bangladesh,Government Budget,2002-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
12,Bangladesh,Government Budget,2003-12-31,-3.70,Yearly,BangladeshGB,2015-06-12 14:23:00
13,Bangladesh,Government Budget,2004-12-31,-3.40,Yearly,BangladeshGB,2015-06-12 14:23:00
14,Bangladesh,Government Budget,2005-12-31,-3.40,Yearly,BangladeshGB,2015-06-12 14:23:00
15,Bangladesh,Government Budget,2006-12-31,-2.80,Yearly,BangladeshGB,2016-03-28 17:01:00
16,Bangladesh,Government Budget,2007-12-31,-2.80,Yearly,BangladeshGB,2016-03-28 17:01:00
17,Bangladesh,Government Budget,2008-12-31,-4.60,Yearly,BangladeshGB,2016-03-28 17:01:00
18,Bangladesh,Government Budget,2009-12-31,-2.80,Yearly,BangladeshGB,2017-01-04 16:22:00
19,Bangladesh,Government Budget,2010-12-31,-3.40,Yearly,BangladeshGB,2017-01-04 16:22:00
20,Bangladesh,Government Budget,2011-12-31,-3.60,Yearly,BangladeshGB,2017-01-04 16:22:00
21,Bangladesh,Government Budget,2012-12-31,-4.00,Yearly,BangladeshGB,2017-01-04 16:21:00
22,Bangladesh,Government Budget,2013-12-31,-3.60,Yearly,BangladeshGB,2017-01-04 16:21:00
23,Bangladesh,Government Budget,2014-12-31,-4.00,Yearly,BangladeshGB,2021-03-02 15:03:00
24,Bangladesh,Government Budget,2015-12-31,-4.50,Yearly,BangladeshGB,2021-03-02 15:03:00
25,Bangladesh,Government Budget,2016-12-31,-4.74,Yearly,BangladeshGB,2022-10-19 07:07:00
26,Bangladesh,Government Budget,2017-12-31,-4.76,Yearly,BangladeshGB,2022-10-19 07:07:00
27,Bangladesh,Government Budget,2018-12-31,4.78,Yearly,BangladeshGB,2022-10-19 07:07:00
28,Bangladesh,Government Budget,2019-12-31,-4.80,Yearly,BangladeshGB,2021-03-02 15:02:00
29,Bangladesh,Government Budget,2020-12-31,-5.48,Yearly,BangladeshGB,2022-10-19 07:06:00
30,Bangladesh,Government Budget,2021-12-31,-6.23,Yearly,BangladeshGB,2022-10-19 07:07:00
31,Bangladesh,Government Budget,2022-12-31,-5.06,Yearly,BangladeshGB,2025-05-26 06:11:00
32,Bangladesh,Government Budget,2023-12-31,-5.00,Yearly,BangladeshGB,2025-05-26 06:11:00
33,Bangladesh,Government Budget,2024-12-31,-4.60,Yearly,BangladeshGB,2025-05-26 06:11:00

In [64]:
government_budget_value = pd.read_csv("../data/tradingeconomics/Government/Government_Budget_Value.csv")

government_budget_value["DateTime"] = pd.to_datetime(government_budget_value["DateTime"], errors='coerce')
government_budget_value["LastUpdate"] = pd.to_datetime(government_budget_value["LastUpdate"], errors='coerce')

government_budget_value

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Budget Value,1995-12-31,-70.05,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
1,Bangladesh,Government Budget Value,1996-12-31,-78.32,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
2,Bangladesh,Government Budget Value,1997-12-31,-66.97,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
3,Bangladesh,Government Budget Value,1998-12-31,-68.39,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
4,Bangladesh,Government Budget Value,1999-12-31,-100.12,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
5,Bangladesh,Government Budget Value,2000-12-31,-143.90,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
6,Bangladesh,Government Budget Value,2001-12-31,-130.57,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
7,Bangladesh,Government Budget Value,2002-12-31,-128.64,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
8,Bangladesh,Government Budget Value,2003-12-31,-109.55,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
9,Bangladesh,Government Budget Value,2004-12-31,-117.84,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
10,Bangladesh,Government Budget Value,2005-12-31,-147.03,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
11,Bangladesh,Government Budget Value,2006-12-31,-195.15,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
12,Bangladesh,Government Budget Value,2007-12-31,-152.14,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
13,Bangladesh,Government Budget Value,2008-12-31,-286.81,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
14,Bangladesh,Government Budget Value,2009-12-31,-200.31,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
15,Bangladesh,Government Budget Value,2010-12-31,-272.97,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
16,Bangladesh,Government Budget Value,2011-12-31,-332.19,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
17,Bangladesh,Government Budget Value,2012-12-31,-341.69,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
18,Bangladesh,Government Budget Value,2013-12-31,-390.06,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
19,Bangladesh,Government Budget Value,2014-12-31,-694.90,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
20,Bangladesh,Government Budget Value,2015-12-31,-652.45,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
21,Bangladesh,Government Budget Value,2016-12-31,-871.64,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
22,Bangladesh,Government Budget Value,2017-12-31,-682.89,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
23,Bangladesh,Government Budget Value,2018-12-31,-1120.41,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
24,Bangladesh,Government Budget Value,2019-12-31,-1259.42,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
25,Bangladesh,Government Budget Value,2020-12-31,-1535.08,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
26,Bangladesh,Government Budget Value,2021-12-31,-1874.51,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
27,Bangladesh,Government Budget Value,2022-12-31,-2045.00,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
28,Bangladesh,Government Budget Value,2023-12-31,-2275.07,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00
29,Bangladesh,Government Budget Value,2024-12-31,-2364.18,Yearly,BANGLADESHGOVBUDVAL,2025-11-06 10:15:00

In [65]:
government_spending = pd.read_csv("../data/tradingeconomics/Government/Government_Spending.csv")

government_spending["DateTime"] = pd.to_datetime(government_spending["DateTime"], errors='coerce')
government_spending["LastUpdate"] = pd.to_datetime(government_spending["LastUpdate"], errors='coerce')

government_spending

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Spending,2016-06-30,1217.5,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
1,Bangladesh,Government Spending,2017-06-30,1305.2,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
2,Bangladesh,Government Spending,2018-06-30,1374.1,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
3,Bangladesh,Government Spending,2019-06-30,1558.2,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
4,Bangladesh,Government Spending,2020-06-30,1588.6,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
5,Bangladesh,Government Spending,2021-06-30,1697.9,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
6,Bangladesh,Government Spending,2022-06-30,1803.9,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
7,Bangladesh,Government Spending,2023-06-30,1957.8,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
8,Bangladesh,Government Spending,2024-06-30,2149.2,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00
9,Bangladesh,Government Spending,2025-06-30,2218.2,Yearly,BANGLADESHGOVSPE,2025-11-13 04:44:00

In [66]:
government_revenues = pd.read_csv("../data/tradingeconomics/Government/Government_Revenues.csv")

government_revenues["DateTime"] = pd.to_datetime(government_revenues["DateTime"], errors='coerce')
government_revenues["LastUpdate"] = pd.to_datetime(government_revenues["LastUpdate"], errors='coerce')

government_revenues

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Government Revenues,1995-12-31,150.08,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
1,Bangladesh,Government Revenues,1996-12-31,153.33,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
2,Bangladesh,Government Revenues,1997-12-31,173.85,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
3,Bangladesh,Government Revenues,1998-12-31,190.20,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
4,Bangladesh,Government Revenues,1999-12-31,197.67,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
5,Bangladesh,Government Revenues,2000-12-31,200.74,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
6,Bangladesh,Government Revenues,2001-12-31,243.42,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
7,Bangladesh,Government Revenues,2002-12-31,278.93,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
8,Bangladesh,Government Revenues,2003-12-31,311.20,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
9,Bangladesh,Government Revenues,2004-12-31,354.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
10,Bangladesh,Government Revenues,2005-12-31,392.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
11,Bangladesh,Government Revenues,2006-12-31,448.68,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
12,Bangladesh,Government Revenues,2007-12-31,516.22,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
13,Bangladesh,Government Revenues,2008-12-31,649.27,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
14,Bangladesh,Government Revenues,2009-12-31,741.09,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
15,Bangladesh,Government Revenues,2010-12-31,832.26,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
16,Bangladesh,Government Revenues,2011-12-31,950.49,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
17,Bangladesh,Government Revenues,2012-12-31,1182.59,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
18,Bangladesh,Government Revenues,2013-12-31,1350.07,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
19,Bangladesh,Government Revenues,2014-12-31,1467.32,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
20,Bangladesh,Government Revenues,2015-12-31,1482.90,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
21,Bangladesh,Government Revenues,2016-12-31,1774.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
22,Bangladesh,Government Revenues,2017-12-31,2012.10,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
23,Bangladesh,Government Revenues,2018-12-31,2594.54,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
24,Bangladesh,Government Revenues,2019-12-31,3165.99,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
25,Bangladesh,Government Revenues,2020-12-31,3480.69,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
26,Bangladesh,Government Revenues,2021-12-31,3515.32,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
27,Bangladesh,Government Revenues,2022-12-31,3890.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
28,Bangladesh,Government Revenues,2023-12-31,4330.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00
29,Bangladesh,Government Revenues,2024-12-31,4780.00,Yearly,BANGLADESHGOVREV,2025-11-06 10:09:00

In [67]:
fiscal_expenditure = pd.read_csv("../data/tradingeconomics/Government/Fiscal_Expenditure.csv")

fiscal_expenditure["DateTime"] = pd.to_datetime(fiscal_expenditure["DateTime"], errors='coerce')
fiscal_expenditure["LastUpdate"] = pd.to_datetime(fiscal_expenditure["LastUpdate"], errors='coerce')

fiscal_expenditure

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Fiscal Expenditure,1995-12-31,220.13,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
1,Bangladesh,Fiscal Expenditure,1996-12-31,231.65,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
2,Bangladesh,Fiscal Expenditure,1997-12-31,240.82,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
3,Bangladesh,Fiscal Expenditure,1998-12-31,258.59,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
4,Bangladesh,Fiscal Expenditure,1999-12-31,297.79,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
5,Bangladesh,Fiscal Expenditure,2000-12-31,344.64,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
6,Bangladesh,Fiscal Expenditure,2001-12-31,373.99,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
7,Bangladesh,Fiscal Expenditure,2002-12-31,407.57,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
8,Bangladesh,Fiscal Expenditure,2003-12-31,420.75,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
9,Bangladesh,Fiscal Expenditure,2004-12-31,471.84,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
10,Bangladesh,Fiscal Expenditure,2005-12-31,539.03,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
11,Bangladesh,Fiscal Expenditure,2006-12-31,643.83,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
12,Bangladesh,Fiscal Expenditure,2007-12-31,668.36,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
13,Bangladesh,Fiscal Expenditure,2008-12-31,936.08,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
14,Bangladesh,Fiscal Expenditure,2009-12-31,941.40,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
15,Bangladesh,Fiscal Expenditure,2010-12-31,1105.23,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
16,Bangladesh,Fiscal Expenditure,2011-12-31,1282.68,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
17,Bangladesh,Fiscal Expenditure,2012-12-31,1524.28,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
18,Bangladesh,Fiscal Expenditure,2013-12-31,1740.13,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
19,Bangladesh,Fiscal Expenditure,2014-12-31,2162.22,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
20,Bangladesh,Fiscal Expenditure,2015-12-31,2135.35,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
21,Bangladesh,Fiscal Expenditure,2016-12-31,2645.64,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
22,Bangladesh,Fiscal Expenditure,2017-12-31,2694.99,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
23,Bangladesh,Fiscal Expenditure,2018-12-31,3714.95,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
24,Bangladesh,Fiscal Expenditure,2019-12-31,4425.41,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
25,Bangladesh,Fiscal Expenditure,2020-12-31,5015.77,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
26,Bangladesh,Fiscal Expenditure,2021-12-31,5389.83,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
27,Bangladesh,Fiscal Expenditure,2022-12-31,5935.00,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
28,Bangladesh,Fiscal Expenditure,2023-12-31,6605.07,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00
29,Bangladesh,Fiscal Expenditure,2024-12-31,7144.18,Yearly,BANGLADESHFISEXP,2025-11-06 09:58:00

In [68]:
corruption_index = pd.read_csv("../data/tradingeconomics/Government/Corruption_Index.csv")

corruption_index["DateTime"] = pd.to_datetime(corruption_index["DateTime"], errors='coerce')
corruption_index["LastUpdate"] = pd.to_datetime(corruption_index["LastUpdate"], errors='coerce')

corruption_index

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Corruption Index,1996-12-31,22.9,Yearly,BangladeshCorInd,2015-06-12 17:30:00
1,Bangladesh,Corruption Index,2001-12-31,4.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
2,Bangladesh,Corruption Index,2002-12-31,12.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
3,Bangladesh,Corruption Index,2003-12-31,13.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
4,Bangladesh,Corruption Index,2004-12-31,15.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
5,Bangladesh,Corruption Index,2005-12-31,17.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
6,Bangladesh,Corruption Index,2006-12-31,20.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
7,Bangladesh,Corruption Index,2007-12-31,20.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
8,Bangladesh,Corruption Index,2008-12-31,21.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
9,Bangladesh,Corruption Index,2009-12-31,24.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
10,Bangladesh,Corruption Index,2010-12-31,24.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
11,Bangladesh,Corruption Index,2011-12-31,27.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
12,Bangladesh,Corruption Index,2012-12-31,26.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
13,Bangladesh,Corruption Index,2013-12-31,27.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
14,Bangladesh,Corruption Index,2014-12-31,25.0,Yearly,BangladeshCorInd,2015-06-12 17:30:00
15,Bangladesh,Corruption Index,2015-12-31,25.0,Yearly,BangladeshCorInd,2016-01-27 16:52:00
16,Bangladesh,Corruption Index,2016-12-31,26.0,Yearly,BangladeshCorInd,2017-02-06 16:48:00
17,Bangladesh,Corruption Index,2017-12-31,28.0,Yearly,BangladeshCorInd,2018-03-13 10:30:00
18,Bangladesh,Corruption Index,2018-12-31,26.0,Yearly,BangladeshCorInd,2019-01-29 12:29:00
19,Bangladesh,Corruption Index,2019-12-31,26.0,Yearly,BangladeshCorInd,2020-01-23 09:43:00
20,Bangladesh,Corruption Index,2020-12-31,26.0,Yearly,BangladeshCorInd,2021-02-02 14:39:00
21,Bangladesh,Corruption Index,2021-12-31,26.0,Yearly,BangladeshCorInd,2022-04-04 10:13:00
22,Bangladesh,Corruption Index,2022-12-31,25.0,Yearly,BangladeshCorInd,2023-01-31 15:36:00
23,Bangladesh,Corruption Index,2023-12-31,24.0,Yearly,BangladeshCorInd,2024-01-30 15:13:00
24,Bangladesh,Corruption Index,2024-12-31,23.0,Yearly,BangladeshCorInd,2025-02-11 09:25:00

In [69]:
corruption_rank = pd.read_csv("../data/tradingeconomics/Government/Corruption_Rank.csv")

corruption_rank["DateTime"] = pd.to_datetime(corruption_rank["DateTime"], errors='coerce')
corruption_rank["LastUpdate"] = pd.to_datetime(corruption_rank["LastUpdate"], errors='coerce')

corruption_rank

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Corruption Rank,1996-12-31,51,Yearly,BangladeshCorRan,2015-06-12 17:37:00
1,Bangladesh,Corruption Rank,2001-12-31,91,Yearly,BangladeshCorRan,2015-06-12 17:37:00
2,Bangladesh,Corruption Rank,2002-12-31,102,Yearly,BangladeshCorRan,2015-06-12 17:37:00
3,Bangladesh,Corruption Rank,2003-12-31,133,Yearly,BangladeshCorRan,2015-06-12 17:37:00
4,Bangladesh,Corruption Rank,2004-12-31,145,Yearly,BangladeshCorRan,2015-06-12 17:37:00
5,Bangladesh,Corruption Rank,2005-12-31,158,Yearly,BangladeshCorRan,2015-06-12 17:37:00
6,Bangladesh,Corruption Rank,2006-12-31,156,Yearly,BangladeshCorRan,2015-06-12 17:37:00
7,Bangladesh,Corruption Rank,2007-12-31,162,Yearly,BangladeshCorRan,2015-06-12 17:37:00
8,Bangladesh,Corruption Rank,2008-12-31,147,Yearly,BangladeshCorRan,2015-06-12 17:37:00
9,Bangladesh,Corruption Rank,2009-12-31,139,Yearly,BangladeshCorRan,2015-06-12 17:37:00
10,Bangladesh,Corruption Rank,2010-12-31,134,Yearly,BangladeshCorRan,2015-06-12 17:37:00
11,Bangladesh,Corruption Rank,2011-12-31,120,Yearly,BangladeshCorRan,2015-06-12 17:37:00
12,Bangladesh,Corruption Rank,2012-12-31,144,Yearly,BangladeshCorRan,2015-06-12 17:37:00
13,Bangladesh,Corruption Rank,2013-12-31,136,Yearly,BangladeshCorRan,2015-06-12 17:37:00
14,Bangladesh,Corruption Rank,2014-12-31,145,Yearly,BangladeshCorRan,2015-06-12 17:37:00
15,Bangladesh,Corruption Rank,2015-12-31,139,Yearly,BangladeshCorRan,2016-01-27 16:52:00
16,Bangladesh,Corruption Rank,2016-12-31,145,Yearly,BangladeshCorRan,2017-01-26 14:34:00
17,Bangladesh,Corruption Rank,2017-12-31,143,Yearly,BangladeshCorRan,2018-03-13 10:30:00
18,Bangladesh,Corruption Rank,2018-12-31,149,Yearly,BangladeshCorRan,2019-01-29 12:19:00
19,Bangladesh,Corruption Rank,2019-12-31,146,Yearly,BangladeshCorRan,2020-01-23 09:45:00
20,Bangladesh,Corruption Rank,2020-12-31,146,Yearly,BangladeshCorRan,2021-02-02 14:20:00
21,Bangladesh,Corruption Rank,2021-12-31,147,Yearly,BangladeshCorRan,2022-04-04 10:48:00
22,Bangladesh,Corruption Rank,2022-12-31,147,Yearly,BangladeshCorRan,2023-01-31 15:50:00
23,Bangladesh,Corruption Rank,2023-12-31,149,Yearly,BangladeshCorRan,2024-01-30 14:57:00
24,Bangladesh,Corruption Rank,2024-12-31,151,Yearly,BangladeshCorRan,2025-02-11 09:27:00

In [70]:
military_expenditure = pd.read_csv("../data/tradingeconomics/Government/Military_Expenditure.csv")

military_expenditure["DateTime"] = pd.to_datetime(military_expenditure["DateTime"], errors='coerce')
military_expenditure["LastUpdate"] = pd.to_datetime(military_expenditure["LastUpdate"], errors='coerce')

military_expenditure

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Military Expenditure,1973-12-31,48.6,Yearly,BangladeshMil,2022-10-05 21:36:00
1,Bangladesh,Military Expenditure,1974-12-31,72.3,Yearly,BangladeshMil,2022-10-05 21:36:00
2,Bangladesh,Military Expenditure,1975-12-31,80.8,Yearly,BangladeshMil,2022-10-05 21:36:00
3,Bangladesh,Military Expenditure,1976-12-31,105.3,Yearly,BangladeshMil,2022-10-05 21:36:00
4,Bangladesh,Military Expenditure,1977-12-31,128.5,Yearly,BangladeshMil,2022-10-05 21:36:00
5,Bangladesh,Military Expenditure,1978-12-31,134.9,Yearly,BangladeshMil,2022-10-05 21:36:00
6,Bangladesh,Military Expenditure,1979-12-31,136.3,Yearly,BangladeshMil,2022-10-05 21:36:00
7,Bangladesh,Military Expenditure,1980-12-31,167.3,Yearly,BangladeshMil,2022-10-05 21:36:00
8,Bangladesh,Military Expenditure,1981-12-31,174.1,Yearly,BangladeshMil,2022-10-05 21:36:00
9,Bangladesh,Military Expenditure,1982-12-31,184.7,Yearly,BangladeshMil,2022-10-05 21:36:00
10,Bangladesh,Military Expenditure,1983-12-31,231.8,Yearly,BangladeshMil,2022-10-05 21:36:00
11,Bangladesh,Military Expenditure,1984-12-31,244.3,Yearly,BangladeshMil,2022-10-05 21:36:00
12,Bangladesh,Military Expenditure,1985-12-31,224.9,Yearly,BangladeshMil,2022-10-05 21:36:00
13,Bangladesh,Military Expenditure,1986-12-31,248.8,Yearly,BangladeshMil,2022-10-05 21:36:00
14,Bangladesh,Military Expenditure,1987-12-31,288.3,Yearly,BangladeshMil,2022-10-05 21:36:00
15,Bangladesh,Military Expenditure,1988-12-31,332.0,Yearly,BangladeshMil,2022-10-05 21:36:00
16,Bangladesh,Military Expenditure,1989-12-31,378.8,Yearly,BangladeshMil,2022-10-05 21:36:00
17,Bangladesh,Military Expenditure,1990-12-31,373.0,Yearly,BangladeshMil,2022-10-05 21:36:00
18,Bangladesh,Military Expenditure,1991-12-31,381.7,Yearly,BangladeshMil,2022-10-05 21:36:00
19,Bangladesh,Military Expenditure,1992-12-31,427.7,Yearly,BangladeshMil,2022-10-05 21:36:00
20,Bangladesh,Military Expenditure,1993-12-31,471.0,Yearly,BangladeshMil,2022-10-05 21:36:00
21,Bangladesh,Military Expenditure,1994-12-31,547.4,Yearly,BangladeshMil,2022-10-05 21:36:00
22,Bangladesh,Military Expenditure,1995-12-31,620.1,Yearly,BangladeshMil,2022-10-05 21:36:00
23,Bangladesh,Military Expenditure,1996-12-31,639.0,Yearly,BangladeshMil,2022-10-05 21:36:00
24,Bangladesh,Military Expenditure,1997-12-31,681.9,Yearly,BangladeshMil,2022-10-05 21:36:00
25,Bangladesh,Military Expenditure,1998-12-31,701.6,Yearly,BangladeshMil,2022-10-05 21:36:00
26,Bangladesh,Military Expenditure,1999-12-31,737.4,Yearly,BangladeshMil,2022-10-05 21:36:00
27,Bangladesh,Military Expenditure,2000-12-31,740.8,Yearly,BangladeshMil,2022-10-05 21:36:00
28,Bangladesh,Military Expenditure,2001-12-31,705.5,Yearly,BangladeshMil,2022-10-05 21:36:00
29,Bangladesh,Military Expenditure,2002-12-31,681.8,Yearly,BangladeshMil,2022-10-05 21:36:00
30,Bangladesh,Military Expenditure,2003-12-31,719.4,Yearly,BangladeshMil,2022-10-05 21:36:00
31,Bangladesh,Military Expenditure,2004-12-31,770.6,Yearly,BangladeshMil,2022-10-05 21:36:00
32,Bangladesh,Military Expenditure,2005-12-31,773.7,Yearly,BangladeshMil,2022-10-05 21:36:00
33,Bangladesh,Military Expenditure,2006-12-31,829.7,Yearly,BangladeshMil,2022-10-05 21:36:00
34,Bangladesh,Military Expenditure,2007-12-31,953.5,Yearly,BangladeshMil,2022-10-05 21:36:00
35,Bangladesh,Military Expenditure,2008-12-31,1030.0,Yearly,BangladeshMil,2022-10-05 21:36:00
36,Bangladesh,Military Expenditure,2009-12-31,1258.8,Yearly,BangladeshMil,2022-10-05 21:36:00
37,Bangladesh,Military Expenditure,2010-12-31,1624.6,Yearly,BangladeshMil,2022-10-05 21:36:00
38,Bangladesh,Military Expenditure,2011-12-31,1801.5,Yearly,BangladeshMil,2022-10-05 21:36:00
39,Bangladesh,Military Expenditure,2012-12-31,1823.4,Yearly,BangladeshMil,2022-10-05 21:36:00
40,Bangladesh,Military Expenditure,2013-12-31,2048.0,Yearly,BangladeshMil,2022-10-05 21:36:00
41,Bangladesh,Military Expenditure,2014-12-31,2356.0,Yearly,BangladeshMil,2022-10-05 21:36:00
42,Bangladesh,Military Expenditure,2015-12-31,2815.3,Yearly,BangladeshMil,2022-10-05 21:36:00
43,Bangladesh,Military Expenditure,2016-12-31,3239.8,Yearly,BangladeshMil,2022-10-05 21:36:00
44,Bangladesh,Military Expenditure,2017-12-31,3266.0,Yearly,BangladeshMil,2022-10-05 21:36:00
45,Bangladesh,Military Expenditure,2018-12-31,3649.6,Yearly,BangladeshMil,2022-10-05 21:36:00
46,Bangladesh,Military Expenditure,2019-12-31,4348.5,Yearly,BangladeshMil,2022-10-05 21:36:00
47,Bangladesh,Military Expenditure,2020-12-31,4651.2,Yearly,BangladeshMil,2023-06-07 02:51:00
48,Bangladesh,Military Expenditure,2021-12-31,4849.9,Yearly,BangladeshMil,2024-04-22 16:20:00
49,Bangladesh,Military Expenditure,2022-12-31,4214.4,Yearly,BangladeshMil,2025-05-05 02:19:00
50,Bangladesh,Military Expenditure,2023-12-31,3782.8,Yearly,BangladeshMil,2025-05-05 02:19:00
51,Bangladesh,Military Expenditure,2024-12-31,4034.6,Yearly,BangladeshMil,2025-05-05 02:18:00

In [71]:
corporate_tax_rate = pd.read_csv("../data/tradingeconomics/Government/Corporate_Tax_Rate.csv")

corporate_tax_rate["DateTime"] = pd.to_datetime(corporate_tax_rate["DateTime"], errors='coerce')
corporate_tax_rate["LastUpdate"] = pd.to_datetime(corporate_tax_rate["LastUpdate"], errors='coerce')

corporate_tax_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Corporate Tax Rate,1997-12-31,40.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
1,Bangladesh,Corporate Tax Rate,1998-12-31,40.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
2,Bangladesh,Corporate Tax Rate,1999-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
3,Bangladesh,Corporate Tax Rate,2000-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
4,Bangladesh,Corporate Tax Rate,2001-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
5,Bangladesh,Corporate Tax Rate,2002-12-31,35.0,Yearly,BGDCORPTAX,2014-09-29 11:31:00
6,Bangladesh,Corporate Tax Rate,2003-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
7,Bangladesh,Corporate Tax Rate,2004-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
8,Bangladesh,Corporate Tax Rate,2005-12-31,30.0,Yearly,BGDCORPTAX,2014-09-29 11:32:00
9,Bangladesh,Corporate Tax Rate,2006-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
10,Bangladesh,Corporate Tax Rate,2007-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
11,Bangladesh,Corporate Tax Rate,2008-12-31,30.0,Yearly,BGDCORPTAX,2013-09-25 16:48:00
12,Bangladesh,Corporate Tax Rate,2009-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
13,Bangladesh,Corporate Tax Rate,2010-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
14,Bangladesh,Corporate Tax Rate,2011-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
15,Bangladesh,Corporate Tax Rate,2012-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
16,Bangladesh,Corporate Tax Rate,2013-12-31,27.5,Yearly,BGDCORPTAX,2013-09-25 16:48:00
17,Bangladesh,Corporate Tax Rate,2014-12-31,27.5,Yearly,BGDCORPTAX,2014-03-24 10:58:00
18,Bangladesh,Corporate Tax Rate,2015-12-31,27.5,Yearly,BGDCORPTAX,2016-03-28 16:33:00
19,Bangladesh,Corporate Tax Rate,2016-12-31,25.0,Yearly,BGDCORPTAX,2016-11-25 15:32:00
20,Bangladesh,Corporate Tax Rate,2017-12-31,25.0,Yearly,BGDCORPTAX,2018-02-09 15:51:00
21,Bangladesh,Corporate Tax Rate,2018-12-31,25.0,Yearly,BGDCORPTAX,2018-02-09 15:51:00
22,Bangladesh,Corporate Tax Rate,2019-12-31,25.0,Yearly,BGDCORPTAX,2020-02-11 16:47:00
23,Bangladesh,Corporate Tax Rate,2020-12-31,25.0,Yearly,BGDCORPTAX,2021-03-02 14:43:00
24,Bangladesh,Corporate Tax Rate,2021-12-31,32.5,Yearly,BGDCORPTAX,2021-06-01 16:19:00
25,Bangladesh,Corporate Tax Rate,2022-12-31,30.0,Yearly,BGDCORPTAX,2022-10-25 01:55:00
26,Bangladesh,Corporate Tax Rate,2023-12-31,27.5,Yearly,BGDCORPTAX,2024-04-15 09:19:00
27,Bangladesh,Corporate Tax Rate,2024-12-31,27.5,Yearly,BGDCORPTAX,2024-04-15 09:15:00
28,Bangladesh,Corporate Tax Rate,2025-12-31,27.5,Yearly,BGDCORPTAX,2025-01-31 09:32:00

In [72]:
personal_income_tax_rate = pd.read_csv("../data/tradingeconomics/Government/Personal_Income_Tax_Rate.csv")

personal_income_tax_rate["DateTime"] = pd.to_datetime(personal_income_tax_rate["DateTime"], errors='coerce')
personal_income_tax_rate["LastUpdate"] = pd.to_datetime(personal_income_tax_rate["LastUpdate"], errors='coerce')

personal_income_tax_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Personal Income Tax Rate,2004-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
1,Bangladesh,Personal Income Tax Rate,2005-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
2,Bangladesh,Personal Income Tax Rate,2006-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
3,Bangladesh,Personal Income Tax Rate,2007-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
4,Bangladesh,Personal Income Tax Rate,2008-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
5,Bangladesh,Personal Income Tax Rate,2009-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
6,Bangladesh,Personal Income Tax Rate,2010-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
7,Bangladesh,Personal Income Tax Rate,2011-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
8,Bangladesh,Personal Income Tax Rate,2012-12-31,25,Yearly,BGDIRSTAX,2013-09-25 12:34:00
9,Bangladesh,Personal Income Tax Rate,2013-12-31,25,Yearly,BGDIRSTAX,2014-03-25 13:17:00
10,Bangladesh,Personal Income Tax Rate,2014-12-31,30,Yearly,BGDIRSTAX,2016-03-08 18:40:00
11,Bangladesh,Personal Income Tax Rate,2015-12-31,30,Yearly,BGDIRSTAX,2016-03-08 18:40:00
12,Bangladesh,Personal Income Tax Rate,2016-12-31,30,Yearly,BGDIRSTAX,2017-01-02 16:52:00
13,Bangladesh,Personal Income Tax Rate,2017-12-31,30,Yearly,BGDIRSTAX,2018-02-09 17:34:00
14,Bangladesh,Personal Income Tax Rate,2018-12-31,30,Yearly,BGDIRSTAX,2018-02-09 17:34:00
15,Bangladesh,Personal Income Tax Rate,2019-12-31,30,Yearly,BGDIRSTAX,2020-02-13 15:14:00
16,Bangladesh,Personal Income Tax Rate,2020-12-31,30,Yearly,BGDIRSTAX,2021-05-10 17:04:00
17,Bangladesh,Personal Income Tax Rate,2021-12-31,25,Yearly,BGDIRSTAX,2021-06-02 08:36:00
18,Bangladesh,Personal Income Tax Rate,2022-12-31,25,Yearly,BGDIRSTAX,2022-10-25 01:57:00
19,Bangladesh,Personal Income Tax Rate,2023-12-31,25,Yearly,BGDIRSTAX,2024-08-19 04:28:00
20,Bangladesh,Personal Income Tax Rate,2024-12-31,25,Yearly,BGDIRSTAX,2024-08-19 04:28:00

In [73]:
sales_tax_rate = pd.read_csv("../data/tradingeconomics/Government/Sales_Tax_Rate.csv")

sales_tax_rate["DateTime"] = pd.to_datetime(sales_tax_rate["DateTime"], errors='coerce')
sales_tax_rate["LastUpdate"] = pd.to_datetime(sales_tax_rate["LastUpdate"], errors='coerce')

sales_tax_rate

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Sales Tax Rate,2006-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
1,Bangladesh,Sales Tax Rate,2007-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
2,Bangladesh,Sales Tax Rate,2008-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
3,Bangladesh,Sales Tax Rate,2009-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
4,Bangladesh,Sales Tax Rate,2010-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
5,Bangladesh,Sales Tax Rate,2011-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
6,Bangladesh,Sales Tax Rate,2012-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
7,Bangladesh,Sales Tax Rate,2013-12-31,15,Yearly,BGDSALESTAX,2013-09-25 16:44:00
8,Bangladesh,Sales Tax Rate,2014-12-31,15,Yearly,BGDSALESTAX,2014-03-20 17:24:00
9,Bangladesh,Sales Tax Rate,2015-12-31,15,Yearly,BGDSALESTAX,2016-03-08 18:33:00
10,Bangladesh,Sales Tax Rate,2016-12-31,15,Yearly,BGDSALESTAX,2016-11-28 15:12:00
11,Bangladesh,Sales Tax Rate,2017-12-31,15,Yearly,BGDSALESTAX,2018-02-06 16:10:00
12,Bangladesh,Sales Tax Rate,2018-12-31,15,Yearly,BGDSALESTAX,2018-02-13 16:23:00
13,Bangladesh,Sales Tax Rate,2019-12-31,15,Yearly,BGDSALESTAX,2019-01-17 10:36:00
14,Bangladesh,Sales Tax Rate,2020-12-31,15,Yearly,BGDSALESTAX,2020-02-12 17:35:00
15,Bangladesh,Sales Tax Rate,2021-12-31,15,Yearly,BGDSALESTAX,2021-08-17 16:01:00
16,Bangladesh,Sales Tax Rate,2022-12-31,15,Yearly,BGDSALESTAX,2022-10-25 01:57:00
17,Bangladesh,Sales Tax Rate,2023-12-31,15,Yearly,BGDSALESTAX,2023-04-05 01:29:00
18,Bangladesh,Sales Tax Rate,2024-12-31,15,Yearly,BGDSALESTAX,2024-08-19 04:27:00
19,Bangladesh,Sales Tax Rate,2025-12-31,15,Yearly,BGDSALESTAX,2025-01-31 08:02:00

<br> <br> 

## Business

In [74]:
manufacturing_production = pd.read_csv("../data/tradingeconomics/Business/Manufacturing_Production.csv")

manufacturing_production["DateTime"] = pd.to_datetime(manufacturing_production["DateTime"], errors='coerce')
manufacturing_production["LastUpdate"] = pd.to_datetime(manufacturing_production["LastUpdate"], errors='coerce')

manufacturing_production

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Manufacturing Production,2013-02-28,3.00,Monthly,BANGLADESHMANPRO,2017-08-28 16:09:00
1,Bangladesh,Manufacturing Production,2013-03-31,9.20,Monthly,BANGLADESHMANPRO,2017-08-28 16:09:00
2,Bangladesh,Manufacturing Production,2013-04-30,10.90,Monthly,BANGLADESHMANPRO,2017-08-28 16:09:00
3,Bangladesh,Manufacturing Production,2013-05-31,13.60,Monthly,BANGLADESHMANPRO,2017-08-28 16:09:00
4,Bangladesh,Manufacturing Production,2013-06-30,11.40,Monthly,BANGLADESHMANPRO,2017-08-28 16:09:00
...,...,...,...,...,...,...,...
148,Bangladesh,Manufacturing Production,2025-06-30,-1.02,Monthly,BANGLADESHMANPRO,2026-01-05 06:03:00
149,Bangladesh,Manufacturing Production,2025-07-31,11.02,Monthly,BANGLADESHMANPRO,2026-01-05 06:03:00
150,Bangladesh,Manufacturing Production,2025-08-31,4.05,Monthly,BANGLADESHMANPRO,2026-01-05 06:04:00
151,Bangladesh,Manufacturing Production,2025-09-30,3.58,Monthly,BANGLADESHMANPRO,2026-01-05 06:04:00
152,Bangladesh,Manufacturing Production,2025-10-31,2.33,Monthly,BANGLADESHMANPRO,2026-01-05 06:04:00

In [75]:
mining_production = pd.read_csv("../data/tradingeconomics/Business/Mining_Production.csv")

mining_production["DateTime"] = pd.to_datetime(mining_production["DateTime"], errors='coerce')
mining_production["LastUpdate"] = pd.to_datetime(mining_production["LastUpdate"], errors='coerce')

mining_production

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Mining Production,2014-04-30,4.10,Monthly,BANGLADESHMINPRO,2017-08-28 16:24:00
1,Bangladesh,Mining Production,2014-05-31,5.00,Monthly,BANGLADESHMINPRO,2017-08-28 16:24:00
2,Bangladesh,Mining Production,2014-06-30,0.80,Monthly,BANGLADESHMINPRO,2017-08-28 16:24:00
3,Bangladesh,Mining Production,2014-07-31,-2.00,Monthly,BANGLADESHMINPRO,2017-08-28 16:24:00
4,Bangladesh,Mining Production,2014-08-31,6.10,Monthly,BANGLADESHMINPRO,2017-08-28 16:24:00
...,...,...,...,...,...,...,...
133,Bangladesh,Mining Production,2025-06-30,-4.26,Monthly,BANGLADESHMINPRO,2025-09-25 08:19:00
134,Bangladesh,Mining Production,2025-07-31,-3.18,Monthly,BANGLADESHMINPRO,2025-09-25 08:17:00
135,Bangladesh,Mining Production,2025-08-31,-14.04,Monthly,BANGLADESHMINPRO,2025-10-29 05:23:00
136,Bangladesh,Mining Production,2025-09-30,-13.48,Monthly,BANGLADESHMINPRO,2025-11-28 03:01:00
137,Bangladesh,Mining Production,2025-10-31,-14.74,Monthly,BANGLADESHMINPRO,2026-01-05 06:06:00

<br> <br> 

## Consumer

In [76]:
consumer_spending = pd.read_csv("../data/tradingeconomics/Consumer/Consumer_Spending.csv")

consumer_spending["DateTime"] = pd.to_datetime(consumer_spending["DateTime"], errors='coerce')
consumer_spending["LastUpdate"] = pd.to_datetime(consumer_spending["LastUpdate"], errors='coerce')

consumer_spending

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Consumer Spending,2016-06-30,13879.9,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
1,Bangladesh,Consumer Spending,2017-06-30,14750.0,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
2,Bangladesh,Consumer Spending,2018-06-30,16138.5,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
3,Bangladesh,Consumer Spending,2019-06-30,16922.1,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
4,Bangladesh,Consumer Spending,2020-06-30,17429.2,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
5,Bangladesh,Consumer Spending,2021-06-30,18826.2,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
6,Bangladesh,Consumer Spending,2022-06-30,20233.7,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
7,Bangladesh,Consumer Spending,2023-06-30,20635.4,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
8,Bangladesh,Consumer Spending,2024-06-30,21871.7,Yearly,BANGLADESHCONSPE,2025-11-13 04:34:00
9,Bangladesh,Consumer Spending,2025-06-30,22914.2,Yearly,BANGLADESHCONSPE,2025-11-13 04:30:00

In [77]:
private_sector_credit = pd.read_csv("../data/tradingeconomics/Consumer/Private_Sector_Credit.csv")

private_sector_credit["DateTime"] = pd.to_datetime(private_sector_credit["DateTime"], errors='coerce')
private_sector_credit["LastUpdate"] = pd.to_datetime(private_sector_credit["LastUpdate"], errors='coerce')

private_sector_credit

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Private Sector Credit,1999-06-30,498.3,Monthly,BANGLADESHPRISECCRE,2025-04-18 06:04:00
1,Bangladesh,Private Sector Credit,2000-06-30,549.5,Monthly,BANGLADESHPRISECCRE,2025-04-18 06:04:00
2,Bangladesh,Private Sector Credit,2001-06-30,638.8,Monthly,BANGLADESHPRISECCRE,2025-04-18 06:04:00
3,Bangladesh,Private Sector Credit,2002-06-30,730.4,Monthly,BANGLADESHPRISECCRE,2025-04-18 06:04:00
4,Bangladesh,Private Sector Credit,2003-06-30,824.0,Monthly,BANGLADESHPRISECCRE,2025-04-18 06:04:00
...,...,...,...,...,...,...,...
169,Bangladesh,Private Sector Credit,2025-06-30,17253.6,Monthly,BANGLADESHPRISECCRE,2025-08-26 04:24:00
170,Bangladesh,Private Sector Credit,2025-07-31,17205.4,Monthly,BANGLADESHPRISECCRE,2025-09-25 03:12:00
171,Bangladesh,Private Sector Credit,2025-08-31,17255.4,Monthly,BANGLADESHPRISECCRE,2025-10-29 05:10:00
172,Bangladesh,Private Sector Credit,2025-09-30,17345.3,Monthly,BANGLADESHPRISECCRE,2025-12-05 04:26:00
173,Bangladesh,Private Sector Credit,2025-10-31,17388.2,Monthly,BANGLADESHPRISECCRE,2026-01-05 06:09:00

In [78]:
consumer_credit = pd.read_csv("../data/tradingeconomics/Consumer/Consumer_Credit.csv")

consumer_credit["DateTime"] = pd.to_datetime(consumer_credit["DateTime"], errors='coerce')
consumer_credit["LastUpdate"] = pd.to_datetime(consumer_credit["LastUpdate"], errors='coerce')

consumer_credit

,Country,Category,DateTime,Value,Frequency,HistoricalDataSymbol,LastUpdate
0,Bangladesh,Consumer Credit,1990-01-31,220.17,Monthly,BANGLADESHCONCRE,2014-11-16 21:28:00
1,Bangladesh,Consumer Credit,1990-02-28,222.50,Monthly,BANGLADESHCONCRE,2014-11-16 21:28:00
2,Bangladesh,Consumer Credit,1990-03-30,221.43,Monthly,BANGLADESHCONCRE,2014-11-16 21:28:00
3,Bangladesh,Consumer Credit,1990-03-31,221.43,Monthly,BANGLADESHCONCRE,2016-06-20 13:39:00
4,Bangladesh,Consumer Credit,1990-04-30,221.37,Monthly,BANGLADESHCONCRE,2014-11-16 21:28:00
...,...,...,...,...,...,...,...
488,Bangladesh,Consumer Credit,2025-06-30,22843.53,Monthly,BANGLADESHCONCRE,2025-09-25 03:10:00
489,Bangladesh,Consumer Credit,2025-07-31,22924.66,Monthly,BANGLADESHCONCRE,2025-09-25 03:10:00
490,Bangladesh,Consumer Credit,2025-08-31,22925.54,Monthly,BANGLADESHCONCRE,2025-10-29 05:04:00
491,Bangladesh,Consumer Credit,2025-09-30,23211.56,Monthly,BANGLADESHCONCRE,2025-12-05 04:04:00
492,Bangladesh,Consumer Credit,2025-10-31,23358.85,Monthly,BANGLADESHCONCRE,2026-01-05 06:08:00